### ISSUE TITLE
New error when opening Ankimon window: "Integer division or modulo by zero"

### ISSUE THREAD

**Issue by ylime0124** [Unlucky-Life/ankimon#101]
Hey, I started getting this error recently. I did download your newest prerelease, but I had started getting this error before doing that.

I've tried resetting all configs to default and restarting Anki but no success. Any thoughts?

<img width="328" alt="image" src="https://github.com/Unlucky-Life/ankimon/assets/69134574/86fbddbf-7958-46f3-bb44-37d31f38aac9">

**Comment by ylime0124** [comment]
Hey update: I figured out this only happens when I'm using Scatterbug as my main Pokémon for some reason. I have no clue why this would be. I've attached the stats from this specific pokémon's mainpokemon.json file if it helps:

[
  {
    "name": "Scatterbug",
    "gender": "M",
    "level": 4,
    "id": 664,
    "ability": "Compound Eyes",
    "type": [
      "Bug"
    ],
    "stats": {
      "hp": 38,
      "atk": 35,
      "def": 40,
      "spa": 27,
      "spd": 25,
      "spe": 35,
      "xp": 35
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 2,
      "atk": 12,
      "def": 14,
      "spa": 11,
      "spd": 10,
      "spe": 25
    },
    "attacks": [
      "stringshot",
      "tackle"
    ],
    "base_experience": 62,
    "current_hp": 17,
    "growth_rate": "medium"
  }
]

**Comment by Unlucky-Life** [comment]
@ylime0124 Hmm somehow the file you had was somehow messed up, here is the new mainpokemon.json that works:
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/15240170/mainpokemon.json)

Could you send me your mypokemon.json file so i can inject the data into your mypokemon collection ?

**Comment by ylime0124** [comment]
Yeah of course, here it is: 
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15243382/mypokemon.json)

Thanks!

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15246667/mypokemon.json)
Here you go :)
