### ISSUE TITLE
Error message: Not sure what type of issue this is...

### ISSUE THREAD

**Issue by strwberrys1234** [Unlucky-Life/ankimon#103]
![image](https://github.com/Unlucky-Life/ankimon/assets/168125785/842d8744-dbb8-49c9-9a93-7ba27ee0f2f8)

Hi Unlucky-Life! I was wondering if you've seen this error message before. I'm honestly not even sure if it's related to ankimon. Just thought I'd ask because you're the only one who would be able to help me troubleshoot. Thank you <3

**Comment by strwberrys1234** [comment]
Also, after reading some of the other posts, I wonder if this has already been brought up. I'm honestly not sure because the threads are way above my head haha

**Comment by Unlucky-Life** [comment]
Hey @strwberrys1234 !
Yes this is propably is an error from Ankimon.
Could you follow up with mor einfos how this message appeared and where ?
(On Anki Start Up ? ; Those it only appear in your reviewer or only against certain Pokemon ?
Those this error only appear with a certain mainpokemon or with with all of the others ?)

For troubleshooting here are some suggestions:
I believe this is propably an issue with a move not corresponding to damage.
=> Try to install the new pre-release: https://github.com/Unlucky-Life/ankimon/releases/tag/1.272
This could solve the issue
Or try to check if this issue happens with other pokemon as well if you switch out your mainpokemon

**Comment by strwberrys1234** [comment]
it was fixed in the latest update! thank you :)
