### ISSUE TITLE
Suggestion: Setting to make hard button deal damage to my own pokemon

### ISSUE THREAD

**Issue by emaad99** [Unlucky-Life/ankimon#104]
Hello, Awesome add-on. I hated Anki until I got this add-on.
Can you add a setting that makes the hard button serve as the again, where the opposing pokemon will damage my pokemon.
I never use again, as this messes up my work flow. My settings are setup so that I use hard as my incorrect button. If I used again, then I would never get through my thousands of cards. Can you add a setting for those of us that use hard as a negative/incorrect button, to do damage to my pokemon, just to make the experience slightly more fun and challenging?

Thank You

**Comment by emaad99** [comment]
Actually I realized it does state in the text pop up that my pokemon should be taking damage when I press hard. However this damage is not reflected in the Ankimon Battle window. The battle window only updates my opponents decreased HP. It shows my pokemon as always at full health.

**Comment by Unlucky-Life** [comment]
@emaad99 Hey yes this issue has been takled already in the prerelease here on github: 
https://github.com/Unlucky-Life/ankimon/releases/tag/1.272
if you download the anki .apkg addon file => double click and install it, the issue should be fixed :)

**Comment by emaad99** [comment]
> @emaad99 Hey yes this issue has been takled already in the prerelease here on github: https://github.com/Unlucky-Life/ankimon/releases/tag/1.272 if you download the anki .apkg addon file => double click and install it, the issue should be fixed :)

You're awesome! thanks man
