### ISSUE TITLE
Anki not opening with error

### ISSUE THREAD

**Issue by OuraN2O** [Unlucky-Life/ankimon#105]
Hi, just installed the new beta (1.273) and anki won't open anymore and an error would show up 
![image](https://github.com/Unlucky-Life/ankimon/assets/151692686/c822be98-b225-490e-85fc-3fd0c602d893)

**Comment by Unlucky-Life** [comment]
@OuraN2O Hey man you were way to fast for me !
Issue is fixed and im uploading the next stable release :) 1.274

**Comment by Unlucky-Life** [comment]
https://github.com/Unlucky-Life/ankimon/releases/download/1.274/ankimon-1.274-anki21-ankiweb.ankiaddon

**Comment by OuraN2O** [comment]
Perfect ahah, thx !
