### ISSUE TITLE
Unable to start Anki due to error

### ISSUE THREAD

**Issue by whitetwinsaber** [Unlucky-Life/ankimon#106]
I have been having this error for the last week, even before the update today. I think it is related to having defeated a level 100+ pokemon and/or catching a level 100+ pokemon.

![image](https://github.com/Unlucky-Life/ankimon/assets/169604202/b1979cba-532e-4f3a-9d7f-054eb16b1034)

**Comment by Unlucky-Life** [comment]
hm ok i see, is your main pokemon right now a pokemon over level 100 ?

**Comment by whitetwinsaber** [comment]
My main pokemon is not over level 100.
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/15301966/mainpokemon.json)

**Comment by Unlucky-Life** [comment]
https://github.com/Unlucky-Life/ankimon/releases/download/1.277/ankimon-1.277-anki21-ankiweb.ankiaddon
@whitetwinsaber 
If you download the file from this url above, this is a quick fix for anki not starting up due to pokemon with a level over 100.
(A proper fix will be added for the next update)

**Comment by whitetwinsaber** [comment]
Thank you for your help! Ankimon is working again. It is still a bit buggy but I assume that will be wrinkled out with the next patch. Once again, thank you!
