### ISSUE TITLE
Renaming Pokemon Mostly Results in Freeze + Question

### ISSUE THREAD

**Issue by sunrucong** [Unlucky-Life/ankimon#107]
Hey Unlucky!

I noticed renaming Pokemon will cause the entire app to freeze, go light screen like right before the "Program is not working" pop-up shows up, and if I don't hit anything, it'll snap back to the original color, though it can stay stuck on that screen and then repeat the same freeze process. Sometimes it fully snaps out of it but sometimes it keeps cycling through that freeze process until I force close it.

Also, are Pokemon Abilities implemented? For instance, Kartana's Beast Boost boosts its highest stat everytime it defeats a Pokemon until it's switched out. Are these stat changes in effect? Because of how I believe the add-on is set up, I'm unable to tell if the variability in damage output is due to some random number generation involved in the damage calculation or if it is having an effect.

Thanks!

**Comment by Unlucky-Life** [comment]
@sunrucong The renaming issue could be due to the amount of pokemon you have. Basically once you rename your pokemon the whole "pokemon collection" window is renewed / recreated. So that might be the issue there. Ill think about how to adjust/ correct this :/.

(Pokemon abilities arent implemented yet. At least their boosting effects (there are just such a vast amount of abilities and diffrent effects that this might be quite alot of work.)

Thanks for the bug report ! Ill check it out!

**Comment by sunrucong** [comment]
Gotcha I see, thanks for getting back to me on the issue! I don't really care for the nicknaming feature but just noticed it and wanted to point it out.

And I totally understand on the Abilities, I would've been very impressed if they were already implemented haha

**Comment by Unlucky-Life** [comment]
@sunrucong Im very thankful for the bugs being reported because the addon and all the features are that big, its hard to test all the issues and features!

(I hope I can find a good file or something that makes the process of abilities easier)

**Comment by sunrucong** [comment]
One quick subquestion - Are IVs implemented in this add-on? They're not that important to me and I wouldn't expect that level of detail from this add-on (at least not yet!), but just wanted to ask cuz right now I'm sitting on several lv. 100 copies of various Pokemon that I just caught cuz I felt like it and if IVs aren't a thing and they're all basically identical I can release a ton of them and hopefully decrease the size of the collection and provide a patchwork fix to this solution, at least for myself!
