### ISSUE TITLE
Can't choose starter pokemon

### ISSUE THREAD

**Issue by AnkitMayank** [Unlucky-Life/ankimon#108]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\ankit\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6157, in <lambda>
    qconnect(fire_starter_button.clicked, lambda: choose_pokemon(fire_start))
  File "C:\Users\ankit\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5010, in choose_pokemon
    mainpokemon_name, mainpokemon_id, mainpokemon_ability, mainpokemon_type, mainpokemon_stats, mainpokemon_attacks, mainpokemon_level, mainpokemon_base_experience, mainpokemon_xp, mainpokemon_hp, mainpokemon_current_hp, mainpokemon_growth_rate, mainpokemon_ev, mainpokemon_iv, mainpokemon_evolutions, mainpokemon_battle_stats, mainpokemon_gender = mainpokemon_data()
ValueError: too many values to unpack (expected 17)

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T20:34, 'None', '']
Advanced Copy Fields Qt6 ['287110490', 2023-11-10T23:52, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-04-18T15:55, 'None', mod]
Anki Killstreaks - Reward Medals for Correct Answers - Fixed by Shige ['1562475180', 2024-05-02T07:24, 'None', mod]
Anki Terminator - ChatGPT Sidebar for Review GoogleBard BingChat by Shige ['1428126516', 2024-01-22T15:39, 'None', mod]
Ankimon by Unlucky-life ['1908235722', 2024-05-12T20:38, 'None', '']
Batch Editing ['291119185', 2023-10-26T06:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T22:25, 'None', '']
Bionic Reading ['649714433', 2023-10-27T03:24, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-31T04:58, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T21:06, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T17:50, 'None', '']
Edit Field During Review Cloze ['385888438', 2024-01-03T13:19, '6.18', mod]
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T22:58, 'None', '']
High Yield Tags ['1918380616', 2023-01-11T01:14, 'None', mod]
Hint Hotkeys ['1844908621', 2023-04-14T20:13, 'None', '']
Hitmarkers ['1776869150', 2024-02-24T17:19, 'None', '']
Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2022-04-09T13:15, 'None', '']
Image Style Editor ['1593969147', 2021-12-17T13:01, 'None', mod]
More Overview Stats 21 ['738807903', 2021-07-31T01:13, 'None', '']
Motivanki ['663438166', 2022-06-23T21:38, 'None', '']
PDF to notes Fixed by Shige ['1660513597', 2024-04-06T11:24, 'None', mod]
ReColor ['688199788', 2024-03-03T07:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-30T07:43, 'None', '']
Show total review count in main screen ['1730200873', 2023-10-14T23:00, 'None', mod]
Special Fields ['1102281552', 2024-03-20T05:34, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T17:24, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-01-27T16:19, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-18T01:28, 'None', mod]

===IDs of active AnkiWeb add-ons===
1046608507 1052724801 1102281552 1135507717 1143540799 1374772155 1428126516 1562475180 1593969147 1660513597 1730200873 1739176371 1771074083 1776869150 1844908621 1908235722 1918380616 287110490 291119185 374005964 385888438 594329229 649714433 663438166 688199788 738807903 864545277 874215009 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['answer-visual-confirmation', 0, 'None', mod]
'' ['popup_dictionary', 0, 'None', '']
AMBOSS add-on ['0amboss_addon', 2022-09-08T18:45, 'None', mod]
Always On Top - permanently keep Anki as top Fixed by Shige ['1045980020', 2024-05-02T07:22, 'None', '']
Always On Top ['1760080335', 2019-06-29T12:45, 'None', '']
Anki Habitica for 21 ['1758045507', 2023-12-16T18:33, 'None', mod]
Anki Zoom ['538879081', 2020-04-04T06:20, 'v1.1.3', mod]
Anki magnifying glass mouse cursor ['842653376', 2022-12-31T18:44, 'None', '']
Anki pop up - After 10 cards take a 3 minute break by Shige ['174058935', 2024-02-15T23:52, 'None', mod]
AnkiBrain AnkiChatGPT - GPT-4 GPT 35 with auto-cards and document analysis ['1915225457', 2024-03-23T10:55, 'None', '']
AnkiConnect ['2055492159', 2024-02-27T10:37, 'None', '']
AnkiHub ['1322529746', 2024-05-07T21:16, 'None', '']
Ankimote - remote to control Anki from your phone ['149004221', 2021-08-11T22:57, 'None', '']
Answer visual  auditory  custom text reinforcement ['976516370', 2024-03-08T15:04, 'None', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-04-15T20:06, 'None', '']
Browser MaximizeHide TableEditorSidebar ['1819291495', 2023-06-24T20:09, 'None', '']
Color Confirmation ['1084228676', 2024-01-06T15:55, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T07:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T15:17, 'None', '']
Exam Notifier ['236593452', 2023-01-19T23:12, 'None', '']
Field AutoComplete ['511710206', 2023-02-26T06:27, 'None', mod]
Google Dictionary ['1346635841', 2022-07-29T03:22, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-22T01:17, 'None', '']
ImageResizer ['1214357311', 2023-12-03T07:58, 'None', '']
Keep model of add cards ['424778276', 2021-10-16T23:36, 'None', '']
Leaderboard ['41708974', 2023-01-15T16:53, 'None', '']
Life Drain ['715575551', 2024-04-30T13:15, 'None', mod]
More Decks Stats and Time Left ['1556734708', 2024-04-11T16:35, 'None', '']
No Distractions Full Screen Fixed for Anki 23 by Shige ['1370336700', 2024-03-05T19:25, 'None', mod]
Opening the same window multiple time ['354407385', 2023-11-05T07:59, 'None', '']
Picmonic Anki Add-On ['40737180', 2024-01-24T22:02, 'None', mod]
Play a celebrationcompletion sound when you finish your deck ['978869609', 2024-01-12T10:43, 'None', mod]
Pokemanki Gold - Raising Pokemon with Anki Fixed by Shige ['1677779223', 2024-05-02T07:31, 'None', '']
Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T12:26, 'None', '']
Progress bar Fixed by Shige ['1708250053', 2024-05-02T07:22, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T18:59, 'None', '']
Remaining time for Anki 21 ['1508357010', 2024-04-16T08:15, '20.12.13i151', mod]
RuneScape-Gamification ['931346754', 2022-12-28T03:06, 'None', '']
Show total time spent in main screen ['1238121460', 2020-07-19T14:36, 'None', '']
Tetris Break for Anki ['1844476877', 2024-02-01T23:56, 'None', mod]
Today Again Count  by Shige ['50293437', 2023-12-13T15:58, 'None', mod]
True Retention ['613684242', 2017-11-20T02:43, 'None', '']
copy note contents to new Add window from Browser Reviewer Add EditCurrent ['759018284', 2022-08-16T16:28, 'None', '']
pasteOCR ['1746010116', 2023-02-27T04:47, 'None', '']

**Comment by Unlucky-Life** [comment]
@AnkitMayank Hey just checked it out and found the bug! Simply just update the Ankimon Addon in your Anki like normally and you should be able to choose your mainpokemon. Or you could simply download the pre release from here and install that for the bug fix aswell: https://github.com/Unlucky-Life/ankimon/releases/tag/1.276

**Comment by AnkitMayank** [comment]
Thank you sir, it's working now
