### ISSUE TITLE
Ankimon not workign as of latest upddate

### ISSUE THREAD

**Issue by Stefflos** [Unlucky-Life/ankimon#109]
Hey there!
First of all! Thanks a million for your wonderful add-on!

Unfortunately something broke today. The error appeared as of the patch I think, because I had it updated recently, but when it appeared there was another update. It's still not working after I updated though.

Providing a printscreen of the error message but that's about what I have I recon.
![image](https://github.com/Unlucky-Life/ankimon/assets/169827457/e8849d3e-431b-4fd5-b9c9-a9cce6512a1c)

Kind regards
Stef

**Comment by Unlucky-Life** [comment]
@Stefflos 
Hey Stef, glad that you like the addon !
Hm, ok lets try to fix this.

Could you send me your `mainpokemon.json` and your `mypokemon.json` files from the user_files folder of the ankimon addon folder ?
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/9d2e0b6f-cd77-4a69-be76-d2f2c9213c94)


Else we can check if its due to the recent update.
You can always download the earlier updates here on github:
https://github.com/Unlucky-Life/ankimon/releases
This was the update you had installed before:

**Comment by Stefflos** [comment]
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/15316302/mainpokemon.json)
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15316303/mypokemon.json)

For info. I was using my macbook last night as well and updating made that one stop working as well.

Kind regards

**Comment by Stefflos** [comment]
New update. I tried completely reinstalling and it works, until I copy my old json files into the whole mixture. So it would seem my json has been corrupted, on both of my anki (with completely different pokemon setups and json files) somehow? 
Is there anything to do to fix it?

**Comment by Unlucky-Life** [comment]
@Stefflos 
So when i copy pasted your files with the newest version i wasnt able to recreate the error message therefore:
I think i might know the issue.

Two steps two troubleshooting.
1. if you havent yet, download the following sprites from this folder: https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites 
And copy the following sprites to your \`user_files`\`sprites`\`back_default` Folder

2. Else if that doesnt work try copy pasting your files back.
There might be an error how a pokemon without a nickname is saved as Null in json.
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15319351/mypokemon.json)
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/15319350/mainpokemon.json)

**Comment by Stefflos** [comment]
Seems to have done the trick with the sprites. Will make a new thread if problem reoccurs. 

Thank you so much for your assistance and keep up the good work! Coffee coming your way!
