### ISSUE TITLE
Big Pokeball logo

### ISSUE THREAD

**Issue by strwberrys1234** [Unlucky-Life/ankimon#110]
![image](https://github.com/Unlucky-Life/ankimon/assets/168125785/f45d2b84-95af-4f12-aa2a-d6fba5dce66a)

Hii @Unlucky-Life, 
After the latest update, I am experiencing a giant pokeball logo after doing a handfull of anki cards. it won't go away unless I exit out of Anki completely, and comes back again after doing a # of cards. Would you be able to help me with this? 

Thank you!

**Comment by Unlucky-Life** [comment]
@strwberrys1234 
Ok, it looks like that the css code didnt properly reintegrate.
Thx fot the bug report !
Let me check that out!

**Comment by Unlucky-Life** [comment]
@strwberrys1234 Also a screenshot of your current ankimon settings would be helpful !

**Comment by Unlucky-Life** [comment]
@strwberrys1234 
Fixed was found, all you need is to install the anki addon package: https://github.com/Unlucky-Life/ankimon/releases/download/1.278/ankimon-1.278-anki21-ankiweb.ankiaddon
