### ISSUE TITLE
Starter not displayed in Pokemon collection and impossible to train other Pokemons 

### ISSUE THREAD

**Issue by Honeywr** [Unlucky-Life/ankimon#111]
Hello ! I just downloaded your add-on and it is AMAZING so far. Quite a difficult task to choose one starter among 7 generations ;) But here is my problem : my starter won't show in my collection and when I try to select another Pokemon to train, a window shows me it has been selected but the ankimon window still shows my starter with each time a different opponent. Thanks in advance for your help ! Keep the good work !
<img width="1440" alt="Capture d’écran 2024-05-14 à 18 53 03" src="https://github.com/Unlucky-Life/ankimon/assets/169832734/e732e46e-5ba6-4fe5-84e4-ffd904e914cb">
<img width="1440" alt="Capture d’écran 2024-05-14 à 18 52 50" src="https://github.com/Unlucky-Life/ankimon/assets/169832734/b9644e39-aaac-48ac-ade4-e7fd39c132c3">

**Comment by Unlucky-Life** [comment]
@Honeywr
1. Thank you for the lovely coment, im happy that you enjoy it!
To the bug: hm ok thats quite weird.
After picking your mainpokemon did you restart Anki yet ?


Could you send me your mainpokemon.json and mypokemon.json files here (they are in the addon folder under user_files) Then i can try to check out the issue :)

**Comment by Honeywr** [comment]
@Unlucky-Life yes, at first there were some bugs, it won't let me choose a starter but the add-on kept my choice anyway and so I just started using it. 
I found the files !! This isn't my thing at all so I'm pretty proud of myself. This is mainpokemon.json : 
[
  {
    "name": "Vulpix",
    "nickname": null,
    "gender": "F",
    "level": 4,
    "id": 37,
    "ability": "Flash Fire",
    "type": [
      "Fire"
    ],
    "stats": {
      "hp": 38,
      "atk": 41,
      "def": 40,
      "spa": 50,
      "spd": 65,
      "spe": 65,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 4,
      "atk": 28,
      "def": 29,
      "spa": 4,
      "spd": 1,
      "spe": 23
    },
    "attacks": [
      "disable",
      "ember"
    ],
    "base_experience": 60,
    "current_hp": 17,
    "growth_rate": "medium"
  }
]

I tried changing my main Pokemon into Vulpinx once. And this is mypokemon.json : 
[
  {
    "name": "Scatterbug",
    "nickname": "",
    "level": 6,
    "gender": "M",
    "id": 664,
    "ability": "Shield Dust",
    "type": [
      "Bug"
    ],
    "stats": {
      "hp": 38,
      "atk": 35,
      "def": 40,
      "spa": 27,
      "spd": 25,
      "spe": 35,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 31,
      "atk": 3,
      "def": 16,
      "spa": 7,
      "spd": 20,
      "spe": 10
    },
    "attacks": [
      "stringshot",
      "stunspore",
      "tackle"
    ],
    "base_experience": 40,
    "current_hp": 24,
    "growth_rate": "medium",
    "evos": []
  },
  {
    "name": "Vulpix",
    "nickname": "",
    "level": 4,
    "gender": "F",
    "id": 37,
    "ability": "Flash Fire",
    "type": [
      "Fire"
    ],
    "stats": {
      "hp": 38,
      "atk": 41,
      "def": 40,
      "spa": 50,
      "spd": 65,
      "spe": 65,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 4,
      "atk": 28,
      "def": 29,
      "spa": 4,
      "spd": 1,
      "spe": 23
    },
    "attacks": [
      "disable",
      "ember"
    ],
    "base_experience": 60,
    "current_hp": 17,
    "growth_rate": "medium",
    "evos": []
  },
  {
    "name": "Hoothoot",
    "nickname": "",
    "level": 5,
    "gender": "F",
    "id": 163,
    "ability": "Insomnia",
    "type": [
      "Normal",
      "Flying"
    ],
    "stats": {
      "hp": 60,
      "atk": 30,
      "def": 30,
      "spa": 36,
      "spd": 56,
      "spe": 50,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 27,
      "atk": 1,
      "def": 32,
      "spa": 3,
      "spd": 24,
      "spe": 23
    },
    "attacks": [
      "growl",
      "tackle"
    ],
    "base_experience": 52,
    "current_hp": 23,
    "growth_rate": "medium",
    "evos": []
  },
  {
    "name": "Pachirisu",
    "nickname": "",
    "level": 4,
    "gender": "M",
    "id": 417,
    "ability": "Run Away",
    "type": [
      "Electric"
    ],
    "stats": {
      "hp": 60,
      "atk": 45,
      "def": 70,
      "spa": 45,
      "spd": 90,
      "spe": 95,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 31,
      "atk": 16,
      "def": 25,
      "spa": 23,
      "spd": 26,
      "spe": 22
    },
    "attacks": [
      "bide",
      "growl",
      "thundershock"
    ],
    "base_experience": 142,
    "current_hp": 21,
    "growth_rate": "medium",
    "evos": []
  },
  {
    "name": "Applin",
    "nickname": "",
    "level": 4,
    "gender": "M",
    "id": 840,
    "ability": "Gluttony",
    "type": [
      "Grass",
      "Dragon"
    ],
    "stats": {
      "hp": 40,
      "atk": 40,
      "def": 80,
      "spa": 40,
      "spd": 40,
      "spe": 20,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 28,
      "atk": 21,
      "def": 18,
      "spa": 24,
      "spd": 14,
      "spe": 24
    },
    "attacks": [
      "astonish",
      "withdraw"
    ],
    "base_experience": 52,
    "current_hp": 19,
    "growth_rate": "medium",
    "evos": []
  },
  {
    "name": "Tapukoko",
    "nickname": "",
    "level": 5,
    "gender": "N",
    "id": 785,
    "ability": "Electric Surge",
    "type": [
      "Electric",
      "Fairy"
    ],
    "stats": {
      "hp": 70,
      "atk": 115,
      "def": 85,
      "spa": 95,
      "spd": 75,
      "spe": 130,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 31,
      "atk": 13,
      "def": 6,
      "spa": 32,
      "spd": 29,
      "spe": 32
    },
    "attacks": [
      "quickattack",
      "thundershock",
      "withdraw"
    ],
    "base_experience": 285,
    "current_hp": 25,
    "growth_rate": "medium",
    "evos": []
  },
  {
    "name": "Solrock",
    "nickname": "",
    "level": 5,
    "gender": "N",
    "id": 338,
    "ability": "Levitate",
    "type": [
      "Rock",
      "Psychic"
    ],
    "stats": {
      "hp": 90,
      "atk": 95,
      "def": 85,
      "spa": 55,
      "spd": 65,
      "spe": 70,
      "xp": 0
    },
    "ev": {
      "hp": 0,
      "atk": 0,
      "def": 0,
      "spa": 0,
      "spd": 0,
      "spe": 0
    },
    "iv": {
      "hp": 30,
      "atk": 6,
      "def": 21,
      "spa": 19,
      "spd": 24,
      "spe": 15
    },
    "attacks": [
      "tackle",
      "morningsun",
      "flareblitz",
      "harden"
    ],
    "base_experience": 161,
    "current_hp": 27,
    "growth_rate": "medium",
    "evos": []
  }
]

Good luck !

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15320791/mypokemon.json)
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/15320792/mainpokemon.json)
No worries :) I have gotten you your starter pokemon back, but just replace those files with these and you have your starter back :)!
I cant tell what that bug was (quite frankly first time someone mentioned this bug).

**Comment by Honeywr** [comment]
@Unlucky-Life it worked ! programming sure is difficult but seems fun when you know what you're doing. Thanks for your time !

**Comment by Unlucky-Life** [comment]
Hey no problem !
