### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by shazzy222** [Unlucky-Life/ankimon#112]
hello!! it comes up with the 'error and troubleshoot' pop-up whenever it tries to update ankimon.
I am on windows.

I love your add-on and really appreciate all the work you do to keep it running and constantly updating with new features/bug fixes! thank you so much!!

debug info:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.addons", line 1203, in _download_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.addons", line 1180, in <lambda>
  File "aqt.addons", line 1196, in _download_all
  File "aqt.addons", line 1141, in download_and_install_addon
  File "aqt.addons", line 467, in install
  File "aqt.addons", line 491, in _install
  File "aqt.addons", line 733, in backupUserFiles
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\(name)\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files' -> 'C:\\Users\\(name)\\AppData\\Roaming\\Anki2\\addons21\\files_backup'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Simulator ['817108664', 2023-11-07T01:26, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-12T22:38, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
Progress bar Fixed by Shige ['1708250053', 2024-05-02T09:22, 'None', mod]
ReColor ['688199788', 2024-03-03T09:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T19:24, 'None', mod]
Straight Reward ['957961234', 2023-11-01T22:11, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 1374772155 1708250053 1771074083 1908235722 688199788 817108664 957961234

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Habitica for 21 ['1758045507', 2023-12-16T20:33, 'None', '']

**Comment by LeonArthurMoegelin** [comment]
Hey @shazzy222 ,
Glad you like the addon !
It seems like there was an issue when installing/updating the addon due to your adminstrator rights: "PermissionError: [WinError 5] Access is denied"
Please try to download the following file: 
=> https://github.com/Unlucky-Life/ankimon/releases/download/1.277/ankimon-1.277-anki21-ankiweb.ankiaddon
An then run this file as admin ! (This is very important - this should allow you to install the addon)
=> Or you need to run Anki as administrator

If this doesnt solve the issue, ill send you the files to copy paste into your ankimon folder directly.
Let me know if it helps !

**Comment by jrsukinik** [comment]
I am having the same issue:

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.addons", line 1242, in _download_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.addons", line 1219, in <lambda>
  File "aqt.addons", line 1235, in _download_all
  File "aqt.addons", line 1180, in download_and_install_addon
  File "aqt.addons", line 469, in install
  File "aqt.addons", line 493, in _install
  File "aqt.addons", line 740, in backupUserFiles
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\jrsuk\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files' -> 'C:\\Users\\jrsuk\\AppData\\Roaming\\Anki2\\addons21\\files_backup'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2998-12-31T18:00, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-12T09:38, 'None', mod]
BetterSearch ['1052724801', 2024-03-06T10:25, 'None', '']
FSRS4Anki Helper ['759844606', 2024-05-13T12:00, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
The KING of Button Add-ons ['374005964', 2024-01-27T04:19, 'None', '']

===IDs of active AnkiWeb add-ons===
1044112126 1052724801 1374772155 1771074083 1908235722 374005964 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Unlucky-Life** [comment]
@jrsukinik did you try the solution above ?
If yes, what was the issue or error ?

Troubleshooting:

Steps to Resolve PermissionError in Anki
Run Anki as Administrator:

Right-click on the Anki shortcut or executable.
Select "Run as administrator."
This should give Anki the necessary permissions to perform file operations in protected directories.
Check File and Folder Permissions:

Navigate to C:\Users\jrsuk\AppData\Roaming\Anki2\addons21\.
Right-click on the addons21 folder and select "Properties."
Go to the "Security" tab and ensure your user account has full control permissions.
If not, click "Edit," select your user account, and check the "Full control" checkbox.

Manual Backup and Install:

Manually back up your pokemons and user files from C:\Users\jrsuk\AppData\Roaming\Anki2\addons21\1908235722\user_files by copying the folder to another location.
Then after backup the user_files folder to another location => Delete the user_files Folder in Ankimon.
Then, try updating the add-on again and after updating, manually copy paste back the above named folder.

**Comment by jrsukinik** [comment]
The manual worked while running as an administrator, nothing else did though.

Thanks!

**Comment by Unlucky-Life** [comment]
@jrsukinik no problem!

**Comment by shazzy222** [comment]
yeah same for me, the manual backup and install option worked. thank you!
