### ISSUE TITLE
pick main pokemon change only opponent

### ISSUE THREAD

**Issue by Mickael103200** [Unlucky-Life/ankimon#113]
hi, recently downloaded ankimon (which is amazing). 
However, whenever i want to change the main pokemon in fight (for better element counter), it only change the enemy pokemon and i have to restart anki for the change to be effective (changing again the enemy pokemon.).

![image](https://github.com/Unlucky-Life/ankimon/assets/170011999/ba6a1836-1b79-4918-8ce4-68edfb3cc604)
![image](https://github.com/Unlucky-Life/ankimon/assets/170011999/62172b0a-5cf8-4f79-aa3f-3f899c894798)
![image](https://github.com/Unlucky-Life/ankimon/assets/170011999/e6bc45b4-6007-471d-9955-1a22922e8f46)
Thank you for your help and the add-on !!!

**Comment by Unlucky-Life** [comment]
@Mickael103200 
Hey, we had this issue already once before with some other user.
Did you restart Anki directly after choosing your starter ?
(An important step to properly save your starter to your mainpokemon collection.

Could you send me your mainpokemon.json and mypokemon.json file ?
(I will propably need to reinject your starter into your mainpokemon file)

**Comment by Unlucky-Life** [comment]
@Mickael103200 
https://github.com/Unlucky-Life/ankimon/releases/download/1.279/ankimon-1.279-anki21-ankiweb.ankiaddon

Bug Fix for not being able to change mainpokemon has been found ^.

**Comment by Mickael103200** [comment]
thank you, the fix totally worked !!
