### ISSUE TITLE
Lost main Pokemon due to bug where it would not switch out mainpokemon. 

### ISSUE THREAD

**Issue by Richzhen15** [Unlucky-Life/ankimon#114]
Pretty self explanatory, but I lost my Buzzswole when switching it out with a smoochum and figured I'd just count my losses until I saw the new update (1.279)

attached are the files requested

[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/15337816/mainpokemon.json)
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15337817/mypokemon.json)

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15338392/mypokemon.json)
There you go ;) => just replace this file with your mypokemon.json and you got your pokemon back !

**Comment by Richzhen15** [comment]
Hi I just switched it in and I think I have the smoochum (is lvl 12 but was lvl 29) back now, but not the Buzzwole (Lvl 28). thanks!!

**Comment by Richzhen15** [comment]
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15339387/mypokemon.json)

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15339524/mypokemon.json)
Here i corrected the levels and added buzzwole (the missing attacks you can relean with "remember attacks" in the Pokemon Details)
