### ISSUE TITLE
Lost a few pokemon, here are requested files 🥲

### ISSUE THREAD

**Issue by missdm0521** [Unlucky-Life/ankimon#115]
Hi unlucky, first wanna say thank you for making such a fun add-on that's really turned around the huge anki burnout I found myself in, you are amazing!!

Lost my meganium about a week ago and entered a period of ~mourning~ and in my very stupid attempt to try to problem solve ended up losing a bunch of other lil guys in the process and now have literally 4 eternatuses 🧍‍♀️  can't even remember the other 2 I lost (ie I had a meganium, eternatus, and 2 others that were replaced by eternatus that I can't remember)

anyway I'll shut up here are the files you requested (pls dont judge my bad choices I've never played pokemon and exclusively choose pokemon & attacks on vibes):
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15351598/mypokemon.json)
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/15351601/mainpokemon.json)

So sorry if you needed any other info I exited out of the update info like a fool, I hope this is enough!!

**Comment by Unlucky-Life** [comment]
Could you tell me their round about level ?

```
meganium, eternatus
```

If you ever remember the other two feel free to hit me back up and ill reinject them ! 

Ill send you the needed files back 2morrow once i know the levels i need to inject them with :)

**Comment by missdm0521** [comment]
Thank you sooo much friend!!  I believe they were both around level 50!  And no worries about the other two, if you can release/delete them from your end that's all good with me :)

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/15365767/mypokemon.json)
Here you go ;) 1x Eternatus lvl 50 and a Meganium lvl 50 has been reinjected and the other 2 eternatus have been removed as you whished. (I hope I understood everything correctly) Else let me know if something is missing or I understood something wrong !

**Comment by missdm0521** [comment]
THAT WORKED THANK YOU SOOO MUCH <3

**Comment by Unlucky-Life** [comment]
Amazing ! Have fun catching :) !
