### ISSUE TITLE
Issues downloading resources

### ISSUE THREAD

**Issue by TheBattleMac** [Unlucky-Life/ankimon#117]
Hey, i have been trying to re-download resources like three times already and each time it gets stuck at any % and never progressed for a hour each time.

Is there a mirror link to get those resources downloaded and put them in their right place?

**Comment by Unlucky-Life** [comment]
If any issues occured go to this page:

https://github.com/Unlucky-Life/ankimon/issues/32

And download the needed files please :)

**Comment by Unlucky-Life** [comment]
If the issue persists, please download the user_files.zip file from this link: https://pixeldrain.com/u/cwd49pLt and unzip this file inside of your user_files Folder to make it look like this:
image

Restart Anki - And Done !

**Comment by TheBattleMac** [comment]
Ok thanks alot, sorry I missed that thread cuz  I found other thread that had expired download link. Thanks alot

**Comment by Unlucky-Life** [comment]
No worries ! :)
