### ISSUE TITLE
Move 'Life Dew' not found.

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#121]
It appeared when I clicked on the "Attack Details" button.
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/d3cad6ae-f604-42f6-96d5-44fb220227a9)

**Comment by Unlucky-Life** [comment]
@Foxy-null Fixed was found in patch 1.281 https://github.com/Unlucky-Life/ankimon/releases/download/1.281/ankimon-1.281-anki21-ankiweb.ankiaddon
