### ISSUE TITLE
Suggestion/question?

### ISSUE THREAD

**Issue by Stefflos** [Unlucky-Life/ankimon#122]
Hello there!
I have been thinking about a little problem of mine and while there are workarounds that are doable but time-consuming I realised it might be quite easy to fix it, but I don't know where to start:

I use anki both my macbook and my desktop (windows) PC, which means my pokedexes won't sync. However if I in some way could reroute the location to where the add-on looks for the json files I could put in in a cloud storage location and it would from there on out be synced.

So 2-fold question: Can you tell me where to locate and edit the data-route (if that's even doable) OR could you perhaps enable an option of picking a specific location for saving/opening the json-files? :)

Thanks again for your great work! Hope the coffee last time was good! :D

Kindest regards Stefflo

**Comment by Unlucky-Life** [comment]
Hey @Stefflos 
Basically you could either directly edit the path inside of the init.py file: 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/4893e47b-4df1-4fc3-9ded-30b58c4d0057)
=> and replace the route with your cloud route :)
Else:
You can simply copy & paste these files "mypokemon.json" and "mainpokemon.json" back and forth.
(aswell as items.json and badges.json)
=> 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/3f31ff56-440b-4662-b4a9-093d9db89a57)

**Comment by Unlucky-Life** [comment]
@Stefflos Its planned tho to be able to sync your pokemon directly to your anki account
