### ISSUE TITLE
Information about the pet hides some text on the card screen when I'm studying on

### ISSUE THREAD

**Issue by sonnk010** [Unlucky-Life/ankimon#123]
Is there an option to turn this information off? I just want to see this in the Ankimon Window
Thank you in advance!

**Comment by Unlucky-Life** [comment]
@sonnk010 Right now you can hide the hp bar, text messages boxes and the info notification :) (check out the options in Ankimon Window)

**Comment by sonnk010** [comment]
Sorry, I don't see the right options. Seems like I missed something
![Screenshot from 2024-05-22 22-36-09](https://github.com/Unlucky-Life/ankimon/assets/40616423/0c835318-ce3e-4fe8-8621-80824b69d42e)

**Comment by Unlucky-Life** [comment]
@sonnk010 my bad, poorly description.
You go to 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/1ddbce20-a42b-4a6e-bdad-5058e1803d11)
(Addons in english)
=> 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/8f2d17f2-b363-48ec-91fc-762c570e9be8)
Then you select Ankimon and click configuration
=> 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/d64c287d-c761-4d37-bef2-005c9d6d5420)
a window where you can configure alot of things :I)
