### ISSUE TITLE
Ankimon overlays card

### ISSUE THREAD

**Issue by rantunesoc** [Unlucky-Life/ankimon#124]
Image attached:

![image](https://github.com/Unlucky-Life/ankimon/assets/89483806/b54c83c6-74c6-4002-89b9-19932819bd13)

**Comment by Unlucky-Life** [comment]
Ah i see. Right now there arent many options for this, either you could create spaces in your card or you can completely hide the ankimon interface inside of the reviewer with the pre release :) 

https://github.com/Unlucky-Life/ankimon/releases/download/1.28/ankimon-1.28-anki21-ankiweb.ankiaddon
