### ISSUE TITLE
How to level up Pokemon?

### ISSUE THREAD

**Issue by dennisb15** [Unlucky-Life/ankimon#125]
Hey I am enjoying this add on, except I cannot figure out how to level up my Pokémon. The XP bar is full but it will not level them up and I cannot find a button to level them up. How do I do it?

**Comment by Unlucky-Life** [comment]
@dennisb15 Usually you would level them up if the xp experience is greater than the experience needed for the next lvl. Could you try to defeat another pokemon and see what happens ?
