### ISSUE TITLE
Following Error occured when opening window: integer division or modulo by zero

### ISSUE THREAD

**Issue by steveTVcze** [Unlucky-Life/ankimon#128]
Hello, your addon is straight up amazing, but today when I tried to open Akimon window I got this error: Following Error occured when opening window: integer division or modulo by zero. Restarting Anki or restarting PC didnt help at all. Is there any way to fix this bug? Thank you so much in advance

**Comment by Unlucky-Life** [comment]
I think i know the issue!

You need the missing sprites apprently

https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites

Download the missing sprites from this folder and place them in the back_default folder, the exact path:  user_files - sprites - back_default

**Comment by steveTVcze** [comment]
It fixed it! Thank you so much
