### ISSUE TITLE
Issue w/Evolution

### ISSUE THREAD

**Issue by mleroux13** [Unlucky-Life/ankimon#130]
Quilava went to evolve but then ran into pop up windows IDing a bug/issue. When prompted I copied the debug info

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.4.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/mattleroux/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1174, in kill_pokemon
    mainpokemon_level = save_main_pokemon_progress(mainpokemon_path, mainpokemon_level, mainpokemon_name, mainpokemon_base_experience, mainpokemon_growth_rate, exp)
  File "/Users/mattleroux/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1455, in save_main_pokemon_progress
    evo_window.display_pokemon_evo(mainpokemon_name.lower())
  File "/Users/mattleroux/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 6405, in display_pokemon_evo
    pokemon_images, evolve_button, dont_evolve_button = self.pokemon_display_evo_pokemon(pkmn_name)
  File "/Users/mattleroux/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 6433, in pokemon_display_evo_pokemon
    pkmnimage_path2 = frontdefault / f"{(pokemon_evo_id)}.png"
UnboundLocalError: local variable 'pokemon_evo_id' referenced before assignment

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T13:01, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T11:34, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-05-20T19:42, 'None', mod]
Anki Remote - Customize ['693153301', 2023-08-26T01:55, 'None', mod]
AnkiHub ['1322529746', 2024-05-30T18:25, 'None', mod]
Ankimon by Unlucky-life ['1908235722', 2024-05-16T12:07, 'None', '']
BetterSearch ['1052724801', 2024-03-06T12:25, 'None', '']
Bionic Reading ['649714433', 2023-10-26T18:24, 'None', mod]
Browser Resizer ['1435775540', 2023-11-11T13:16, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T07:18, 'None', '']
Clickable Tags v20 original ['380714095', 2022-01-30T18:58, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T12:06, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T22:19, 'None', mod]
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-05-21T01:19, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T08:47, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-21T16:17, 'None', '']
Hint Hotkeys ['1844908621', 2023-04-14T11:13, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T04:15, 'None', '']
ImageResizer ['1214357311', 2023-12-02T21:58, 'None', '']
New Cards Counter ['635082046', 2022-04-20T17:37, 'None', '']
ReColor ['688199788', 2024-03-02T21:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']
Special Fields ['1102281552', 2024-03-19T20:34, 'None', mod]
Symbols As You Type updated for 2310 ['1957191470', 2023-12-16T11:27, 'None', '']
Symbols ['1461102936', 2024-02-10T12:53, 'None', mod]
Transfer scheduling data from one card to another Fixed by Shige ['274502770', 2024-03-03T10:05, 'None', '']
uworld_qid_to_anki_search ['607963104', 2023-09-21T12:18, 'None', '']

===IDs of active AnkiWeb add-ons===
1052724801 1102281552 1210908941 1214357311 1322529746 1374772155 1435775540 1461102936 1771074083 1844908621 1908235722 1957191470 225180905 2494384865 274502770 380714095 46611790 594329229 607963104 635082046 649714433 688199788 693153301 759844606 874215009 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Batch Editing ['291119185', 2023-10-25T21:38, 'None', '']
Leaderboard ['41708974', 2023-01-15T06:53, 'None', mod]
More Decks Stats and Time Left ['1556734708', 2024-04-11T07:35, 'None', '']
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2023-01-23T21:59, 'None', '']
Placeholder- SCwCD ['390813456', 2022-11-26T11:55, 'None', '']
Quick tagging 21 ['304770511', 2020-02-11T02:17, 'None', '']
Straight Reward ['957961234', 2023-10-31T14:08, 'None', '']
Symbols As You Type FIXED ['2088399109', 2023-12-14T14:45, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T01:42, 'None', '']
The KING of Button Add-ons ['374005964', 2024-01-27T06:19, 'None', mod]
True Retention ['613684242', 2017-11-19T16:43, 'None', '']

**Comment by Unlucky-Life** [comment]
@mleroux13 hmm i see -> let me check that out ! Thx for the bug report !

**Comment by Unlucky-Life** [comment]
if you like you can send me your  mypokemon.json and mainpokemon.json file and ill help out evolve your quilava !
