### ISSUE TITLE
Error on catching Pokemon (update life bar not defined

### ISSUE THREAD

**Issue by coogy12** [Unlucky-Life/ankimon#131]
Encountered this error on catching my first Pokemon 

 File "/Users/. /Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1824, in catch_pokemon
    new_pokemon()  # Show a new random Pokémon
  File "/Users/. /Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1881, in new_pokemon
    update_life_bar(reviewer, 0, 0)
NameError: name 'update_life_bar' is not defined

**Comment by Unlucky-Life** [comment]
@coogy12 Did you restart your anki yet after choosing your mainpokemon.json ?
If not try that first. Else If that issue persists let me know !

**Comment by Unlucky-Life** [comment]
@coogy12 I also recommend to download the latest pre release :) https://github.com/Unlucky-Life/ankimon/releases/tag/1.287 -> download the .ankiaddon file and double click to install the update !

**Comment by coogy12** [comment]
@Unlucky-Life I had not done that yet and it seems to have fixed everything. I actually started on the pre release as the original release was not working for me due to the divide by zero error mentioned on another thread. I just went ahead and downloaded the entire pre-release to fix that issue.

**Comment by Unlucky-Life** [comment]
ok perfect! Have fun using Ankimon ! :) (The divide by zero issue is basically due to missing sprites in the "back_default" folder -> these u need to download extra under: https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites and place them into your "back_default" folder inside of the sprites folder.

**Comment by coogy12** [comment]
@Unlucky-Life yeah I read that on the other error post, but those sprites were not sufficient to fix my problem. My sprites folder that you say the missing files should be installed to only had sprites 1 and 2 and the missing files only contained sprites numbered in the 600s. So I just downloaded the entire pre released version to get all the other sprites.
