### ISSUE TITLE
Pokemon HP never increasing after leveling up

### ISSUE THREAD

**Issue by madisonruppert** [Unlucky-Life/ankimon#132]
Once you level up quite a bit, Pokemon's HP remains at the same point before leveling up, keeping it at 50% or even lower forever with no way to heal it back.

**Comment by Unlucky-Life** [comment]
Hey @madisonruppert,
Yes thats true -> You can heal it back with items or once your mainpokemon is defeated in a battle -> you will approach another pokemon and your mainpokemon will be healed. (Thats currently how ankimon is set up.
Hope that helps!
