### ISSUE TITLE
All wild Pokemon showing fighting type in the bottom left

### ISSUE THREAD

**Issue by coogy12** [Unlucky-Life/ankimon#134]
The issue is as the title describes. All the Pokemon I encounter are labeled as fighting type in the bottom left of the Anki card screen. This is regardless of the actual type of the Pokemon.

**Comment by jrsukinik** [comment]
It doesn't describe the type, more the status of the opponent pokemon. It would said poisoned if you poisoned the opponent. It just means that its fighting you.
