### ISSUE TITLE
Bug to start Ankimon

### ISSUE THREAD

**Issue by Heidi-FR** [Unlucky-Life/ankimon#135]
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-10.14.6-x86_64-i386-64bit

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 29, in <module>
    from PyQt6.QtGui import *
ModuleNotFoundError: No module named 'PyQt6'

<img width="620" alt="Capture d’écran 2024-06-06 à 17 39 17" src="https://github.com/Unlucky-Life/ankimon/assets/171957661/367c6f00-d2bb-4d49-854c-49c94f4d26fc">

I don't have the choice to download something, do you know how I can fix this ? Thank you so much !

**Comment by Unlucky-Life** [comment]
It seems like you need the Anki Version with PyQt6. That should fix the issue :)

**Comment by Heidi-FR** [comment]
Oh Thanks ! Does it exist for Mac OS 10.14 ?
Thank you so so much !

**Comment by Unlucky-Life** [comment]
Yes https://github.com/ankitects/anki/releases/download/24.04.1/anki-24.04.1-mac-intel-qt6.dmg here you go :)

**Comment by Unlucky-Life** [comment]
@Heidi-FR I am not sure - right now I am not sure. You might need to try one of the following old updates: https://apps.ankiweb.net/downloads/archive/ -> and make sure to check if it has qt6 ! 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/58cb0f18-7a84-4763-a434-373c036f4123)

**Comment by Unlucky-Life** [comment]
It seems like qt6 is only supported for Versiond above MacOS 10 :/
