### ISSUE TITLE
AnkiMon Window Failing to open

### ISSUE THREAD

**Issue by CYPEpic** [Unlucky-Life/ankimon#137]
Hey!

Have an issue opening my ankimon window. Ive attached the error code ive been getting. It basically says: "
Following Error occured when opening window: integer division or modulo by zero"

<img width="257" alt="Screenshot 2024-06-12 at 4 25 42 PM" src="https://github.com/Unlucky-Life/ankimon/assets/172544445/2e38debf-3109-408c-a880-77b313220599">

**Comment by Unlucky-Life** [comment]
@CYPEpic This is a common error: Simply download the sprite files here in the missing_sprites folder: https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
And copy them to the user_files -> sprites -> back_default Folder
this should solve the issue :)

**Comment by CYPEpic** [comment]
It worked! thanks for your help
