### ISSUE TITLE
I dont know why it bugs out randomly when i start a deck, worked perfectly for the first day

### ISSUE THREAD

**Issue by kasig005** [Unlucky-Life/ankimon#138]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 537, in after_answer
  File "aqt.reviewer", line 547, in _after_answering
  File "_aqt.hooks", line 4173, in __call__
  File "C:\Users\kasig\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 4916, in update_life_bar
    experience_for_next_lvl = find_experience_for_level(mainpokemon_growth_rate, mainpokemon_level)
  File "C:\Users\kasig\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 4068, in find_experience_for_level
    return experience
UnboundLocalError: local variable 'experience' referenced before assignment

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnKing Note Types Easy Customization ['952691989', 2024-06-10T11:23, 'None', '']
Anki Killstreaks - Reward Medals for Correct Answers - Fixed by Shige ['1562475180', 2024-05-02T02:24, 'None', '']
Anki Simulator ['817108664', 2023-11-06T17:26, 'None', '']
AnkiBrain AnkiChatGPT - GPT-4 GPT 35 with auto-cards and document analysis ['1915225457', 2024-03-23T04:55, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-16T16:07, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T12:50, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T02:19, 'None', mod]
Deadline2 ['723639202', 2024-02-26T03:38, 'None', mod]
HyperTTS - Add speech to your flashcards ['111623432', 2024-06-01T15:02, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T08:15, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T18:00, 'None', '']
No Distractions Full Screen Fixed for Anki 23 by Shige ['1370336700', 2024-03-05T13:25, 'None', mod]
Pomotroid timer ['106396876', 2020-07-05T19:58, 'None', '']
Random Sprites ['897478712', 2022-01-24T07:38, 'None', '']
Remaining time for Anki 21 ['1508357010', 2024-04-16T03:15, '24.4.16i24', '']
Remove card history ['2089200096', 2023-10-19T04:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
Review Hotmouse ['1928346827', 2024-01-03T05:51, '2.8', mod]
Simple Timer and Stopwatch Fixed for Anki24 by Shige ['2041168053', 2024-04-08T11:57, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T11:24, 'None', '']
Study Time Stats ['1247171202', 2024-02-24T16:59, 'None', '']
True Retention ['613684242', 2017-11-19T20:43, 'None', '']
export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2024-03-28T13:16, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 106396876 111623432 1143540799 1210908941 1247171202 1370336700 1374772155 1508357010 1562475180 1771074083 1908235722 1915225457 1928346827 1967530655 2041168053 2089200096 295889520 613684242 723639202 817108664 897478712 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

Here a bug report i just coppied maybe it might be helpful?

**Comment by Unlucky-Life** [comment]
@kasig005 
Looks like an issue with your pokemons level.
What level is your mainpokemon ?
https://github.com/Unlucky-Life/ankimon/releases/download/1.288/ankimon-1.288-anki21-ankiweb.ankiaddon
=> Else try installing this prerealease and check if it helps out.
