### ISSUE TITLE
Ankimote implementation is not working for me

### ISSUE THREAD

**Issue by CarlosJavierOrozco** [Unlucky-Life/ankimon#139]
My ankimote config.json: 

{
  "feedback": true,
  "cmd1-label": "Suspend Card",
  "cmd1": "mw.reviewer.onSuspendCard()",
  "cmd2-label": "Catch",
  "cmd2": "mw.catchpokemon()",
  "cmd3-label": "Deafeat",
  "cmd3": "mw.defeatpokemon()",
  "cmd4-label": "CMD 4",
  "cmd4": "showInfo('CMD 4: replace with custom code in the Anki addon config page')",
  "cmd5-label": "CMD 5",
  "cmd5": "mw.web.eval( \"alert('CMD 5: replace with custom code in the Anki addon config page');\" )"
}

I have the last release of ankimon

Not sure what happen 🤔🤔🤔😵‍💫

**Comment by Unlucky-Life** [comment]
can you explain what steps you have to use the ankimote ?

**Comment by CarlosJavierOrozco** [comment]
> can you explain what steps you have done to setup the use of the ankimote ?

Thanks for reply! 

My bad! It works extremely well!

**Comment by Unlucky-Life** [comment]
Ah nice, so the issue is solved ? :D

**Comment by CarlosJavierOrozco** [comment]
> Ah nice, so the issue is solved ? :D

Yes!, it was just my mistake!
