### ISSUE TITLE
Hope the experience bar can be displayed

### ISSUE THREAD

**Issue by lxmwwl** [Unlucky-Life/ankimon#141]

**Comment by Unlucky-Life** [comment]
Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config

Here you got a whole lot of options to choose from

**Comment by lxmwwl** [comment]
> Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config
> 
> Here you got a whole lot of options to choose from

Sorry, I have some misunderstandings about the function. I found that after defeating a Pokémon, the experience bar did not change. I was wondering if I could display the experience bar in the form of a progress bar.

**Comment by lxmwwl** [comment]
> Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config是 => 在 anki 的插件管理器窗口中查看，选择 Ankimon by Unlucky-life，然后单击 config
> 
> Here you got a whole lot of options to choose from在这里你有很多选项可供选择

![image](https://github.com/Unlucky-Life/ankimon/assets/124525616/2c2bd7d2-1843-46b0-a94e-c9d1cb0d54ae)

**Comment by lxmwwl** [comment]
> > > Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config是 => 在 anki 的插件管理器窗口中查看，选择 Ankimon by Unlucky-life，然后单击 config
> > > Here you got a whole lot of options to choose from在这里你有很多选项可供选择
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/124525616/340580228-2c2bd7d2-1843-46b0-a94e-c9d1cb0d54ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYwNDAsIm5iZiI6MTcxODY5NTc0MCwicGF0aCI6Ii8xMjQ1MjU2MTYvMzQwNTgwMjI4LTJjMmJkN2QyLTE4NDMtNDZiMC1hOTRlLWM5ZDFjYjBkNTRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNzI5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTgwNDRkYzg2OWM1NWRjOTBiOWIzMmRiM2FmZWNkODBkZDJjMzEwMjZjNWQ4ZDdkNDAyOGM0YzkxZTg2ZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l5dl6iILbdkJdtHunstSF2RmH-Y0ZxadGdqEGOovDOc)
> > I don’t know why the extra progress bar cannot be displayed. It is not displayed until the progress bar is smaller than this width. I hope it can be improved.不知道为什么额外的进度条无法显示。直到进度条小于这个宽度才显示。我希望它能够得到改进。
> 
> > > Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config
> > > Here you got a whole lot of options to choose from
> > 
> > 
> Just like this, these two are the same interface, but I reduced the window



> > Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config
> > Here you got a whole lot of options to choose from
> 
> ![image](https://private-user-images.githubusercontent.com/124525616/340580228-2c2bd7d2-1843-46b0-a94e-c9d1cb0d54ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYwNDAsIm5iZiI6MTcxODY5NTc0MCwicGF0aCI6Ii8xMjQ1MjU2MTYvMzQwNTgwMjI4LTJjMmJkN2QyLTE4NDMtNDZiMC1hOTRlLWM5ZDFjYjBkNTRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNzI5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTgwNDRkYzg2OWM1NWRjOTBiOWIzMmRiM2FmZWNkODBkZDJjMzEwMjZjNWQ4ZDdkNDAyOGM0YzkxZTg2ZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l5dl6iILbdkJdtHunstSF2RmH-Y0ZxadGdqEGOovDOc)
> 
> I don’t know why the extra progress bar cannot be displayed. It is not displayed until the progress bar is smaller than this width. I hope it can be improved.



> > Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config
> > Here you got a whole lot of options to choose from
> 
> ![image](https://private-user-images.githubusercontent.com/124525616/340580228-2c2bd7d2-1843-46b0-a94e-c9d1cb0d54ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYwNDAsIm5iZiI6MTcxODY5NTc0MCwicGF0aCI6Ii8xMjQ1MjU2MTYvMzQwNTgwMjI4LTJjMmJkN2QyLTE4NDMtNDZiMC1hOTRlLWM5ZDFjYjBkNTRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNzI5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTgwNDRkYzg2OWM1NWRjOTBiOWIzMmRiM2FmZWNkODBkZDJjMzEwMjZjNWQ4ZDdkNDAyOGM0YzkxZTg2ZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l5dl6iILbdkJdtHunstSF2RmH-Y0ZxadGdqEGOovDOc)
> 
> I don’t know why the extra progress bar cannot be displayed. It is not displayed until the progress bar is smaller than this width. I hope it can be improved.
![Uploading 20240618_153058_030_copy.png…]()
![Uploading 20240618_153107_967_copy.png…]()

Just like this, these two are the same interface, but I reduced the window

**Comment by lxmwwl** [comment]
> > Yes => check out in the addon manager window in anki select Ankimon by Unlucky-life and then click config
> > Here you got a whole lot of options to choose from
> 
> ![image](https://private-user-images.githubusercontent.com/124525616/340580228-2c2bd7d2-1843-46b0-a94e-c9d1cb0d54ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTYwNDAsIm5iZiI6MTcxODY5NTc0MCwicGF0aCI6Ii8xMjQ1MjU2MTYvMzQwNTgwMjI4LTJjMmJkN2QyLTE4NDMtNDZiMC1hOTRlLWM5ZDFjYjBkNTRhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNzI5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTgwNDRkYzg2OWM1NWRjOTBiOWIzMmRiM2FmZWNkODBkZDJjMzEwMjZjNWQ4ZDdkNDAyOGM0YzkxZTg2ZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l5dl6iILbdkJdtHunstSF2RmH-Y0ZxadGdqEGOovDOc)
> 
> I don’t know why the extra progress bar cannot be displayed. It is not displayed until the progress bar is smaller than this width. I hope it can be improved.

![Uploading 20240618_153058_030_copy.png…]()
![Uploading 20240618_153107_967_copy.png…]()

Just like this, these two are the same interface, but I reduced the window

**Comment by Unlucky-Life** [comment]
@lxmwwl ITs actually not a progress bar but instead the xp you need for the next lvl. I believe that its not updating per card properly. (Also there is a bug where sometimes you dont gain xp)

**Comment by Unlucky-Life** [comment]
@lxmwwl If you havent yet, try download the latest release here on github, and install it. That may help
