### ISSUE TITLE
The width of xp progress bar and hp progress bar is wrong

### ISSUE THREAD

**Issue by lxmwwl** [Unlucky-Life/ankimon#142]
<img width="1280" alt="20240618_173557_022_copy" src="https://github.com/Unlucky-Life/ankimon/assets/124525616/b58e6cdc-ed33-4e26-99d7-3c23eb6e4977">
<img width="1280" alt="20240618_173621_176_copy" src="https://github.com/Unlucky-Life/ankimon/assets/124525616/f1d0ef1e-8324-4aa0-88d9-55f6e81a2ca4">
<img width="1280" alt="20240618_173608_699_copy" src="https://github.com/Unlucky-Life/ankimon/assets/124525616/2485044b-2bcd-4fcc-b438-639ba1becf92">
<img width="1280" alt="20240618_173627_362_copy" src="https://github.com/Unlucky-Life/ankimon/assets/124525616/c9a175b8-4bac-44fb-b89e-3d55b68975b3">

As shown in the picture, there is a problem with the width of the progress bar.

**Comment by Unlucky-Life** [comment]
@lxmwwl ah ok i see. Thanks for the heads up !
I think this could be due to the reviewer not updating the html maybe when resizing the window
