### ISSUE TITLE
Can't open ankimon window

### ISSUE THREAD

**Issue by DunzzHMU** [Unlucky-Life/ankimon#145]
When i pick my pokemon Xerneas as main Pokemon, A bug appears :"Following Error occured when opening window: integer division or modulo by zero" then i can't open the ankimon window :">

**Comment by Unlucky-Life** [comment]
This is a common error: Simply download the sprite files here in the missing_sprites folder: https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
And copy them to the user_files -> sprites -> back_default Folder
this should solve the issue :)
