### ISSUE TITLE
Time Increments Missing for Review Buttons in v1.288

### ISSUE THREAD

**Issue by Ankiholic** [Unlucky-Life/ankimon#148]
I have encountered an issue with the most recent update v1.288. When reviewing cards, the time increments for the review buttons (Again, Hard, Good, Easy) do not display. This seems to block or hide the usual time intervals associated with each button (e.g., Hard: two months, Again: five minutes). There also isn't the number of new, learning, and review card numbers left to finish in the deck displayed at the bottom like it normally would either.

This functionality is important as it influences my decision-making during reviews. Attached is an image for reference.

<img width="412" alt="image" src="https://github.com/Unlucky-Life/ankimon/assets/173546808/4136aa68-9d9d-4ca3-9717-90f934650be8">

Overall the update is amazing visually I love your work!!

**Comment by Unlucky-Life** [comment]
@Ankiholic Hm ok thats weird => do you have some other addon installed aswell ? This looks like a addon like "button confirmation". Else try setting 'ankimon_buttons' in the settings as false => that maybe resolves the issue. Else id recommend to disable the "styling_in_reviewer" and to only use the ankimon window.
This could be another addon that changes the internal reviewer code.
(you could try disabling addons that do something in your reviewer and check if that could also be the issue)

**Comment by Unlucky-Life** [comment]
@Ankiholic and btw: if you like to animate your pokemon ins reviewer: 

"Pokemon Gif Animations:
You can decide if you want the Gif Animations in the anki reviewer
- `reviewer_image_gif` [True/False]

**Comment by Ankiholic** [comment]
setting 'ankimon_buttons' in the settings as false helped put my button format back and is now good! And yes, the pokemon gif in reviewer is so good, I cannot thank you enough for the work on this add-on, it's a serious game changer for motivational study!
