### ISSUE TITLE
Starter Pokemon removed and replaced by caught Pokemon 

### ISSUE THREAD

**Issue by nurkittel** [Unlucky-Life/ankimon#15]
My starter Pokemon got replaced by a caught Pokemon and is gone now, furthermore I have two identical copies of that freshly caught Pokemon. I did klick on 'Pick as main Pokemon' while the Ankimon Window didn't close by itself after I defeated that Pokemon. Had to manually close the Ankimon window to continue. 

<img width="782" alt="Screenshot 2024-03-11 at 11 43 07" src="https://github.com/Unlucky-Life/ankimon/assets/83577787/e97bdb62-4fb9-4d89-86b4-16f9dea1bce2">

**Comment by Unlucky-Life** [comment]
Ok this is new bug i havent seen yet / new that that could happen

**Comment by Unlucky-Life** [comment]
Can you explain what exactly happened ?

**Comment by nurkittel** [comment]
Defeated Pontya -> switched to Ankimon window -> clicked on 'catch pokemon' -> Rainbowwheel appears for like 5 seconds then popup ...you caught Ponyta -> Switched back to my flashcard -> clicked 'show pokemon collection' -> choose Ponyta 'pick as my main Pokemon' -> got the popup 'main pokemon chosen ' -> switched back to Ankimon window -> still the same screen with 'Defeat pokemon' 'Catch pokemon' Nickname ... -> clicked defeat -> rainbow wheel 5 seconds -> popup 'you got exp ... and your Charmander (my starter pokemon) is lvl 7 now' -> Still the same screen -> clicked 'catch pokemon again' -> popup 'you already have that pokemon....' -> still same screen -> closed entire Ankimon window -> clicked 'show pokemon collection' and got that 2 times Ponyta and no starter pokemon :(

**Comment by nurkittel** [comment]
Why is the rainbow wheel spinning on my Mac?
How to stop the spinning wheel on Mac
Other names are rainbow wheel, beach ball, or circle of death. The ball signifies that your Mac cannot handle all the tasks given to it at this moment. Every app on your Mac has a so-called window server. When an app receives more events than it can process, the window server automatically shows you the spinning ball. 
I am on a 2021 M1 8GB MacBook Air

**Comment by Unlucky-Life** [comment]
Ok please send me your mypokemon.json and mainpokemon.json over discord or here and i will resend you the pokemon collection with your lost charmander :)

**Comment by nurkittel** [comment]
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/14558083/mainpokemon.json)
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/14558084/mypokemon.json)

**Comment by Unlucky-Life** [comment]
Ahhh ok i understand now how it happened- if you already caught pokemone- you can not defeat the pokemon after that 


- if you chose a diffrent pokemon while in pokemon defeat screen - then press defeat pokemon - it overrides the old main pokemons data in your collection

Conclusion: 
1. Do not change Main Pokemon while in Defeat Screen and Press defeat pokemon

You can always simply close the ankimon window while in review and by reviewing two new cards - it will display a new pokemon by itself - then simply reopen ankimon window with new pokemon
(If you would have the same issue)

**Comment by Unlucky-Life** [comment]
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/14564530/mainpokemon.json)
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/14564531/mypokemon.json)

**Comment by Unlucky-Life** [comment]
Hey you go and get your Charmander back :) - before placing in the files - close anki => then open the folder where the addon files are located => and overwrite the mypokemon.json and mainpokemon.json file
