### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by bravado61** [Unlucky-Life/ankimon#152]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19041

Traceback (most recent call last):
  File "C:\Users\chang\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2807, in <lambda>
    choose_pokemon_button.clicked.connect(lambda state, name=pokemon_name, nickname=pokemon_nickname, level=pokemon_level, id=pokemon_id, ability=pokemon_ability, type=pokemon_type, detail_stats=pokemon_stats, attacks=pokemon_attacks, hp=pokemon_hp, base_experience=pokemon_base_experience, growth_rate=pokemon_growth_rate, ev=pokemon_ev, iv=pokemon_iv, gender=pokemon_gender: MainPokemon(name, nickname, level, id, ability, type, detail_stats, attacks, hp, base_experience, growth_rate, ev, iv, gender))
  File "C:\Users\chang\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 3641, in MainPokemon
    new_pokemon() #new pokemon if you change your pokemon
  File "C:\Users\chang\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1862, in new_pokemon
    update_life_bar(reviewer, 0, 0)
NameError: name 'update_life_bar' is not defined

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T12:01, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-16T10:07, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-06-22T00:05, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T02:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
UpToDate Addon ['utd_anki_addon', 2023-05-08T10:16, 'None', '']

===IDs of active AnkiWeb add-ons===
1374772155 1771074083 1908235722 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Unlucky-Life** [comment]
@bravado61 Could you provide more information on how this bug happened ?
