### ISSUE TITLE
No Damage to my Pokémon

### ISSUE THREAD

**Issue by Goennjamim** [Unlucky-Life/ankimon#154]
My Pokémon dont take any damage while doing Ankicards/fighting random Pokemons. Is that normal?

**Comment by Unlucky-Life** [comment]
Yes, aslong as you dont change the setting "dmg_in_reviewer " to true in the Addon Manager => Ankimon => Configuration

Set dmg_in_reviewer to false if you prefer a simplified interaction. Setting it to true introduces a more realistic experience: once you press again or exert more pressure, the wild Pokémon gains the ability to attack your Pokémon. - dmg_in_reviewer [True/False]
