### ISSUE TITLE
Pass/Fail 2: Remove the "Easy" and "Hard" buttons

### ISSUE THREAD

**Issue by Renanrois** [Unlucky-Life/ankimon#158]
First of all, my sincere thanks for the work on this addon. The idea is very good.

1- I think I have a bug that I don't know how to fix. I use Anki with the addon "Pass/Fail 2: Remove the "Easy" and "Hard" buttons", so I only have two options: 'again (fail)' and 'good (pass)'. It turns out that the 'again' option has the same effect as 'good': it damages the opponent's Pokémon and not mine. Is this correct?

2 - I use a 'dark' template on Anki. Would it be possible to have a version of Ankimon that works with a 'dark' backscreen?

**Comment by Unlucky-Life** [comment]
Hi @Renanrois 

To number 1:
=> Yes its correct that you still attack the opponent pokemon but you to set "dmg_in_reviewer" to true in the Ankimon settings

To number 2:
=> Yea possible => If you set your Anki to "dark Theme" in the Anki Settings it should work :) I am using the Anki Dark Theme and dont have any issues.
Else you can edit the Ankimon HTML by adding certain CSS classes to your Card Templates

Hope that helps !
