### ISSUE TITLE
Bug with Yveltal?

### ISSUE THREAD

**Issue by lucaswobeto** [Unlucky-Life/ankimon#159]
Hey guys, I don't know if it only occurs with Yveltal because I've only tried a few Pokémon as my main Pokémon, but every time I choose Yveltal as my main Pokémon, it crashes the plugin when I open the Ankimon Window. I can't catch or defeat Pokémon with the window closed because if I click on catch or defeat, the plugin crashes too. I can fight the Pokémon until they reach 0 life, but I can't do anything after that.

When I change it back to Arceus, Mew, or Mewtwo, which are the Pokémon I am upgrading, it works fine. I already uninstalled and reinstalled the plugin, but it didn't work either.

**Comment by Unlucky-Life** [comment]
You might need the missing sprites:

https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites

They are all included in this folder
=> try pasting into the following folder

user_files/sprites/back_default/

That might fix the issue

**Comment by lucaswobeto** [comment]
It solved the issue. Thank you! Only one more thing, I've noticed that Pokémon stats don't improve when they level up. Is this normal?

**Comment by Unlucky-Life** [comment]
Yea i think its not properly integrated

Basically you gain ev and iv stats
And these are added on top of your base stats
