### ISSUE TITLE
Testing Pre-Release of Level Cap Removal Bug While Reviewing

### ISSUE THREAD

**Issue by sunrucong** [Unlucky-Life/ankimon#161]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 127, in wrapped_done
  File "aqt.reviewer", line 537, in after_answer
  File "aqt.reviewer", line 547, in _after_answering
  File "_aqt.hooks", line 4173, in __call__
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5104, in update_life_bar
    experience_for_next_lvl = find_experience_for_level(mainpokemon_growth_rate, mainpokemon_level)
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 4338, in find_experience_for_level
    return experience
UnboundLocalError: local variable 'experience' referenced before assignment

Error in sys.excepthook:
Traceback (most recent call last):

Original exception was:
Traceback (most recent call last):

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS Official  Medical School Step  Shelf Study Resource ['1044112126', 2998-12-31T19:00, 'None', '']
AnkiCraft ['ankicraft', 0, 'None', mod]
AnkiHub ['1322529746', 2024-07-09T13:26, 'None', '']
Ankimon ['1908235722', 0, 'None', mod]
Audiovisual Feedback ['231569866', 2023-07-08T23:34, '0.8', mod]
BetterSearch ['1052724801', 2024-03-06T11:25, 'None', '']
Clickable Tags v20 ['1739176371', 2022-01-30T17:58, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
Customize Keyboard Shortcuts ['24411424', 2023-11-01T05:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T02:19, '6.18', mod]
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-07-09T08:54, 'None', mod]
Find cards from UWorld test ['444814983', 2024-07-09T03:36, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-04-11T06:35, 'None', '']
More Overview Stats 21 ['738807903', 2021-07-30T15:13, 'None', '']
Quick tagging 21 ['304770511', 2020-02-11T01:17, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
Search in formatted text in any fields ['1126516755', 2021-10-16T13:37, 'None', '']
The KING of Button Add-ons ['374005964', 2024-01-27T05:19, 'None', mod]
Today Again Count  by Shige ['50293437', 2023-12-13T04:58, 'None', '']
True Retention ['613684242', 2017-11-19T15:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1044112126 1052724801 1126516755 1322529746 1374772155 1556734708 1739176371 1771074083 1908235722 231569866 24411424 304770511 374005964 385888438 444814983 50293437 594329229 613684242 738807903 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T10:34, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-06-10T06:23, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T12:26, 'None', '']
Bionic Reading ['649714433', 2023-10-26T17:24, 'None', mod]
Exam Notifier ['236593452', 2023-01-19T12:12, 'None', '']
ImageResizer ['1214357311', 2023-12-02T20:58, 'None', '']
Pokemanki Gold - Raising Pokemon with Anki Forked by Shige ['1677779223', 2024-06-23T03:04, 'None', '']

**Comment by Unlucky-Life** [comment]
https://github.com/Unlucky-Life/ankimon/releases/download/main-141fdbc5/ankimon-V1.33-anki21-ankiweb.ankiaddon

Fix was found :)
