### ISSUE TITLE
Trouble Remembering Moves

### ISSUE THREAD

**Issue by ADEKBC** [Unlucky-Life/ankimon#162]
When I try to remember moves to change my Pokemon's set, the moves do not refresh. I've tried selecting/remembering the moves and then reselecting the Pokemon as my main, but the new moves never get added, and I am stuck with the same 4 pre-existing moves. Specifically, I am having this issue with my Dialga, but I have had this issue with other Pokemon. In the past, I have been able to circumvent the problem by remembering the moves repeatedly, along with reselecting the Pokemon over and over, and eventually, the change would get made, but that does not seem to work anymore. It doesn't seem limited to any one move, either. I can't get any move to change.

**Comment by ADEKBC** [comment]
I just noticed that if I switch to a new Pokemon in between, the moves seem to update. I added the moves to my Dialga, selected another Pokemon as main, went back and selected the Dialga, and the moves were updated. This seems a little indirect, but it is a solution.

**Comment by Ankiholic** [comment]
I think I had this too but from memory even though it updated visually, the pokemon still uses the same old moves i think.

**Comment by Unlucky-Life** [comment]
@Ankiholic @ADEKBC Thats correct you need to close the details window of the pokemon and then reopen them to view the "updated" pokemon details 

Sorry for the late response, right now I'm in exam preparation and only got that little time!

So the question I would ask here is:
Does it actually "not update" the attacks code-wise, or does it just say that in the current window that is still open ?

**Comment by Ankiholic** [comment]
Yeah all good if you swap main pokemon and then back it all fixes itself!
