### ISSUE TITLE
Traded Pokemon Not Working

### ISSUE THREAD

**Issue by Pazz789** [Unlucky-Life/ankimon#163]
I traded a Rhyhorn with my mate for a Buzzwole and he tried using the Buzzwole but when the pokemon tried to attack it said that the moveset wasn't found

**Comment by Unlucky-Life** [comment]
Hey @Pazz789,
Sorry for the late response,
That sounds a past error there was with the AnkiWeb Version of Ankimon.
I recommend downloading the following pre-release:
[Pre Release with Trading Fix](https://github.com/Unlucky-Life/ankimon/releases/download/1.288/ankimon-1.288-anki21-ankiweb.ankiaddon 
)
When downloading the file, just double click to install.
Once thats done, just restart Anki and the issue should be solved.

**Comment by Unlucky-Life** [comment]
I hope that helps, else let me know !
