### ISSUE TITLE
[Minor] Partial Pokémon Images in Pokédex info and Ankimon Main Window.

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#17]
Some images of large Pokémon are partially cut off in the Pokédex and the Ankimon main window. (Not happening in the Pokédex list screen).

### Screenshots

![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/8e95f8a0-306a-4d07-aa1c-ddd7d0b3f8c4)

![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/c369567d-49bf-4a79-978d-471ee3f8e21e)

![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/d6d9dcb3-64e7-4854-ba93-19913a18580d)

**Comment by Unlucky-Life** [comment]
the slight cut off was intented for design purposes - else the window would have looked a big off maybe

**Comment by Foxy-null** [comment]
I see, now I am convinced why. Thank you for the explanation.
