### ISSUE TITLE
Downloading Resources no response.

### ISSUE THREAD

**Issue by DoubleW2w** [Unlucky-Life/ankimon#172]
![image](https://github.com/user-attachments/assets/dd5a6189-aed9-4677-ada7-8070ec96c56d)

downloading resource but no response。

Can you provide a way to install plugins locally。

this plugin is from https://github.com/Unlucky-Life/ankimon/releases/tag/1.288 , and i install it locally.

**Comment by Unlucky-Life** [comment]
If you have downloaded and installed the plug from the link you presented, you dont need to download any more files :) 👍

**Comment by DoubleW2w** [comment]
> If you have downloaded and installed the plug from the link you presented, you dont need to download any more files :) 👍

thanks !
