### ISSUE TITLE
Can't open Ankimon window but i can still see pokemons when i review cards

### ISSUE THREAD

**Issue by AgentoSid** [Unlucky-Life/ankimon#173]
one morning when starting anki i got this error code. I can't open the Ankimon window but when i review cards, i can still see the pokemons in the bottom left corner. 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\sarah.DESKTOP-HKSUFBQ\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 6016, in <module>
    badge_list = json.load(json_file)
  File "json", line 293, in load
  File "json", line 346, in loads
  File "json.decoder", line 337, in decode
  File "json.decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Unlucky-Life** [comment]
Hi @AgentoSid ,
this looks like an Issue with the badge_list file.
Please got your Ankimon Folder under: `C:\Users\sarah.DESKTOP-HKSUFBQ\AppData\Roaming\Anki2\addons21\1908235722\user_files` and copy the badges.json file here in the Issue (Simple Drag and Drop). At first so you can use Ankimon again you can drag and drop this file:
[badges.json](https://github.com/user-attachments/files/16625005/badges.json)

Ill check out the file and let you know if something else needs to be edited 👍 !
