### ISSUE TITLE
Main Pokemon barely takes any damage from opponent Pokemon

### ISSUE THREAD

**Issue by Facadery** [Unlucky-Life/ankimon#175]
I wanted to say I love this add-on, and thank you so much @Unlucky-Life for developing it! I have a problem with the damage in the reviewer, where there's a 0.0x multiplier when I press "Again" on the card, and both my Pokemon and the opponent does very little damage (often 1 damage). Is there a way to fix this? Thank you in advance!

Screenshot:
![image](https://github.com/user-attachments/assets/0acdb867-39f4-42d4-8feb-858dbada6610)

**Comment by Unlucky-Life** [comment]
Hi @Facadery !
So this is set so there wont be an "infinite hell loop" if both pokemons dont have any damaging moves.
You could only really fix that when editing the code :/. BTW - Have you set "damage to Main Pokemon" to true in the Ankimon settings ?
Hope that Helps !

**Comment by Facadery** [comment]
If you mean dmg in reviewer in the Config, then I have set that to true. I am not sure about "damage to Main Pokemon" though. Thank you for the prompt response!

**Comment by Unlucky-Life** [comment]
@Facadery Yea so set the config already, thats good! But I may check out this issue in the future :). Thanks for the feedback !
