### ISSUE TITLE
Following error occured when opening window:integer division or modulo by zero

### ISSUE THREAD

**Issue by tomplayer07** [Unlucky-Life/ankimon#177]
I know there was already this issue in may and it was closed, but it happened again to me. My froakie evolved into frogadier, and I was asked to select a move but it was a bit bugged and I selected 4 times to not change the new move for old ones. After that, I can't open the ankimon window anymore and I get the title error.

**Comment by Unlucky-Life** [comment]
@tomplayer07 No worries this is an easy fix

  => This means you are missing some back sprites which you can manually install by going to
https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
Download the missing sprites from this folder and place them in 'back_default' under 'sprites / user_files'  in the Ankimon Addon Folder

**Comment by tomplayer07** [comment]
@Unlucky-Life Yay it works, thank you! May I ask if you plan on adding gyms? It would be so cool!

**Comment by Unlucky-Life** [comment]
Yes definently - right now dont really have the time though :/ propably november ill try working on that!
