### ISSUE TITLE
Weird Pokemon spawn rates

### ISSUE THREAD

**Issue by ADEKBC** [Unlucky-Life/ankimon#178]
I've been using Ankimon for a while now, and it seems that, without fail, the Ultra Beasts are showing up wayyy more often than pretty much any other Pokemon. I've counted how many times I've seen the Ultra Beast Pokemon, and each has been at least 50 times (except Naganadel; weirdly, I haven't seen this one at all). Additionally, I've seen more rare Pokemon, like Arceus, probably a dozen times, but other more common/not legendary/mythical/sub-legendary Pokemon have never been seen. However, plenty of sub-legendary Pokemon like those from Gen IX also haven't appeared yet, despite the fact that I've completed enough cards to have seen **thousands of** of Pokemon through the add-on. I don't think the Pokemon's appearance rate is calibrated correctly if that's something that can be changed.

**Comment by Unlucky-Life** [comment]
@ADEKBC its important to restart your Anki from each studying session => Ankimon counts with every Anki Start the number of cards learned => So if Anki isnt restarted => the card counter isnt reset either, therefore you will have alot of legendary pokemon. You can increase the threshhold of the legendary pokemon or ultra by setting the card_counter to 3 or 4 => this will increase the threshhold for the rare pokemon

**Comment by cr7goatoa-art** [comment]
I believe that thisis ultra beast specific as it is happening to me as well maybe an error in the source code?
