### ISSUE TITLE
Pokemon Generations Problem

### ISSUE THREAD

**Issue by LilDubu** [Unlucky-Life/ankimon#179]
Hi there. I have decided to disable every generation but generation I to focus on catching everything in generation I for now. I have noticed that Pokemon from other generations are still showing. 

There doesn't seem to be a fixed amount of generation I Pokemons I must encounter before encountering Pokemon from other generations. Sometimes I encounter 5 generation I in a row, followed by 1-2 Pokemon from other generations. Sometimes it's 1-2.

It's not that big of a problem, but just wanted to let you know.

Additionally, how do I "save" my progress? In the case that there is a bug or I want to transfer the data to another computer, how would I be able to do so?

P.S. Thank you so much for this add-on. It has helped me a lot in doing my Anki cards. Doing >1k cards a day daily makes me want to commit seppuku, but this makes it significantly more tolerable & pretty fun actually. Cheers!

**Comment by Unlucky-Life** [comment]
@LilDubu Hm about the Pokemon Encounter, it should only show for generation I with the national dex Id from 1 - 152, so cant really tell if just was poorly written or not 🗡️ . But make sure to close Anki after each day using it - else the card counter wont reset and you will see the same pokemon from the same tier.

About Backup your progress => you just need to copy the following files in the Ankimon Folder und "user_files" => mypokemon.json, mainpokemon.json, badges.json, items.json =>  and copy them to a diffrent location.

Last prelrelease allows you to sync your pokemon data between computers:[PreRelease]( https://github.com/Unlucky-Life/ankimon/releases/tag/main-e5c115ce)

Just make sure to back up your above named files before updating and to install - just double click when the .ankiaddon file is downloaded.

Glad you like the addon ! More interesting stuff coming aswell later this year! Cheers to you aswell!
