### ISSUE TITLE
No XP being gained or damage being taken

### ISSUE THREAD

**Issue by shimshady17** [Unlucky-Life/ankimon#180]
When I am completing cards, I am not gaining any XP nor am I taking any damage. What should I do to fix this?

**Comment by shimshady17** [comment]
to clarify, this only happens when i have the ankimon window open. When I have it closed, it works as intended.

**Comment by Unlucky-Life** [comment]
Hi @shimshady17!
Not sure to be honest, I did encounter that issue aswell sometimes.
Are you using the latest AnkiWeb release or the latest GitHub PreRelease ?
