### ISSUE TITLE
how to i download ankimon into my anki Version ⁨2.1.66 (70506aeb)⁩ Python 3.9.15 Qt 6.5.2 PyQt 6.5.2

### ISSUE THREAD

**Issue by Taebubbles** [Unlucky-Life/ankimon#187]
hii the code doesnt work for me and i downloaded the ankimon file but i dont know how to add on , so sorry im really bad with coding and tech i dont understand which file is for what thank you!

**Comment by Unlucky-Life** [comment]
sadly your Anki Version might be to old for Ankimon => It looks you just need to update your Anki to a new Version !
![image](https://github.com/user-attachments/assets/169e774b-7dd6-4187-b0b5-0c8ad2e69c84)
^This is from the AnkiWeb Page letting you know, that you need to have atleast Anki Version 23.10

Just go to: https://apps.ankiweb.net/ and download the latest anki Version :) Hope that helps ! (Make sure to install the PyQt6 Version !)
