### ISSUE TITLE
error

### ISSUE THREAD

**Issue by will4347** [Unlucky-Life/ankimon#188]
What should i do with this

<img width="263" alt="IMG_7520" src="https://github.com/user-attachments/assets/84a17772-a9a5-42e2-bfce-67f1a08f9f63">

**Comment by Unlucky-Life** [comment]
Hi @will4347 !
This is a common error:
 => This means you are missing some back sprites which you can manually install by going to
https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
Download the missing sprites from this folder and place them in 'back_default' under 'sprites / user_files'  in the Ankimon Addon Folder

Hope that helps, else let me know !
