### ISSUE TITLE
Deactive the wild pokemon in the review screen

### ISSUE THREAD

**Issue by tih101** [Unlucky-Life/ankimon#189]
is there a way to deactive the wild pokemon in the review screen and leave it to the ankimon window only? I really loved the app but it keeps distracting me

**Comment by Unlucky-Life** [comment]
sorry not rlly - but you can deactivate the styling in reviewer completely with this release: 
https://github.com/Unlucky-Life/ankimon/releases/download/1.288/ankimon-1.288-anki21-ankiweb.ankiaddon
just download and double click to install

**Comment by Unlucky-Life** [comment]
Hope that helps @tih101 !
