### ISSUE TITLE
New enemy Pokemon spawns with 0hp

### ISSUE THREAD

**Issue by nurkittel** [Unlucky-Life/ankimon#19]
After I defeated one and clicked defeat, the Mac rainbow wheel appeared, popup with my Pokemon level up and after that the defeated/catch/nickname screen did not disappear. Usually the next pokemon appeared. Closed the Window. Now every new Pokemon appears with 0hp and can be defeated, I get exp and the next pokemon appears with 0hp. 

<img width="545" alt="Screenshot 2024-03-12 at 17 22 41" src="https://github.com/Unlucky-Life/ankimon/assets/83577787/e7dcfbc6-6001-4019-9c4d-dabf8ad01409">

**Comment by nurkittel** [comment]
Anki restart solved that bug.

**Comment by Unlucky-Life** [comment]
might be a specifiy generate_random pokemon issue
