### ISSUE TITLE
Ankimon window broke after evolution

### ISSUE THREAD

**Issue by NoodleBirb** [Unlucky-Life/ankimon#193]
I evolved my starter after it hit level 16, but I noticed it hadn't change to frogadier in the actual ankimon window. Because of this, I went to the pokemon collection and set frogadier as my main pokemon. After which, it crashed anki, and caused me to be unable to change my main pokemon or open the ankimon window. 
![image](https://github.com/user-attachments/assets/df07aafd-b775-4aa5-97c6-081fad09ae43)
![image](https://github.com/user-attachments/assets/15713c19-16f7-46b4-a91a-96d1f8663ff4)
First error is when I attempt to open the ankimon window.
Second error occurs whenever I try to change my main pokemon.

My frogadier does appear to level up still, I just can't access the main window or change my main pokemon.

**Comment by Unlucky-Life** [comment]
hi @NoodleBirb 
This is an easy fix:

This means you are missing some back sprites which you can manually install by going to
https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
Download the missing sprites from this folder and place them in 'back_default' under 'sprites / user_files'  in the Ankimon Addon Folder

**Comment by NoodleBirb** [comment]
Thank you so much! Worked like a charm!
