### ISSUE TITLE
wild pokemon HP bug

### ISSUE THREAD

**Issue by leahjeffrey** [Unlucky-Life/ankimon#196]
A wild happiny must have used some kind of healing move (I didn't look at which one) and increased its HP above its base (had 45/35), or some other bug of the HP bar

EDIT TO ADD: I reset anki, but in the next battle after my pokemon fainted it had -25/36 HP

**Comment by Unlucky-Life** [comment]
@leahjeffrey Yea, its sadly a error that does happen from time to time and I cant properly tell why this is happening, im really sorry... I could imagine it could be reset if you go to the pokemon collection window => and "repick" your mainpokemon - meaning press the choose as mainpokemon
