### ISSUE TITLE
Error opening the Ankimon window : integer division or modulo by zero

### ISSUE THREAD

**Issue by samuelvitry** [Unlucky-Life/ankimon#201]
When I open anki, the lower bar show up, with a pokemon, I can fight it but when I try to open the ankimon window, this error show up: "Following Error occured when opening window: integer division or modulo by zero"

![image](https://github.com/user-attachments/assets/71c372af-ec6b-47fa-82f0-18df80023801)

I'm on linux, specificaly zorin os 16 but I don't think that matter

I'm on anki version ⁨24.06.3 (d678e393)⁩ and on the latest update of ankimon

I tried restarting anki with no luck

**Comment by Unlucky-Life** [comment]
Its a quick fix: This means you are missing some back sprites which you can manually install by going to
https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
Download the missing sprites from this folder and place them in 'back_default' under 'sprites / user_files'  in the Ankimon Addon Folder

**Comment by samuelvitry** [comment]
Thanks a lot, btw love the addon, thank you for increasing my amount of card per day by 10 time, keep up the good work, if I may suggest a feature, that's probably already been suggested to you, I would love to have a view of how much of the pokedex I've captured, like a number that show that I've captured for exemple 256/1025 pokemon.

**Comment by Unlucky-Life** [comment]
@samuelvitry Glad you like it ! This is planned for the next update 😄 ; But you can visit the discord and check out the latest post on what all planned - the discord is linked on the AnkiWeb !
