### ISSUE TITLE
Opening Ankimon window gives TypeErrors and crashes Anki

### ISSUE THREAD

**Issue by demiaus** [Unlucky-Life/ankimon#202]
```
Following Error occured when opening window: arguments did not match any overloaded call:
  drawRect(self, rect: QRectF): argument 1 has unexpected type 'int'
  drawRect(self, x: int, y: int, w: int, h: int): argument 3 has unexpected type 'float'
  drawRect(self, r: QRect): argument 1 has unexpected type 'int'

```

On Arch Linux.
Affects at least prereleases 1.32 and 1.33.

Maybe related #201

**Comment by Unlucky-Life** [comment]
Hey @demiaus!
Thanks for looking into the code!

The issue rather not in the code itself but instead missing sprites - Its a quick fix: This means you are missing some back sprites which you can manually install by going to
https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
Download the missing sprites from this folder and place them in 'back_default' under 'sprites / user_files' in the Ankimon Addon Folder => The error resolves after adding the missing images.
