### ISSUE TITLE
Overlapping buttons with Anki 24.10

### ISSUE THREAD

**Issue by xip0enix** [Unlucky-Life/ankimon#210]
Hi there,
I recently updated Anki to 24.10 beta 2 and since then the ankimon buttons overlap with the official buttons. My operating system is Windows 11.

![image](https://github.com/user-attachments/assets/d7123157-e8f6-43fb-8434-9e6e52563750)
![image](https://github.com/user-attachments/assets/1eafcf6d-8e5b-4b11-aeac-e82792273c93)

**Comment by Unlucky-Life** [comment]
@xip0enix Ok I see thanks for letting me know ! => You can deactivate the Buttons in the Settings :)!

**Comment by xip0enix** [comment]
I don't know how it happened, but my problem is gone.
