### ISSUE TITLE
Evolved a Pokemon with an item, but deleted my starter.

### ISSUE THREAD

**Issue by JerryLan123** [Unlucky-Life/ankimon#213]
I evolved an onyx into a steelix using a metal coat and what ended up happening was the onyx successfully evolved, but it also turned my starter into a steelix as well.

**Comment by zdanielp** [comment]
I evolved an electabuzz with same results.

**Comment by Unlucky-Life** [comment]
Just drop your mypokemon.json and mainpokemon.json file here 

And i can reimburse them for you 👀👌
Just let me know what pokemon it was and lvl they were at.

You can find the files in the Ankimon Folder - 📁 - just go to Addons => Show Files and then to user_files - there should be two files called mainpokemon.json and mypokemon.json.
You can add them here as an answer :)!

Glad to help out 👌
Sincerly,
Unlucky

**Comment by JerryLan123** [comment]
Appreciate it, here they are! Would I just delete my old ones and just download the ones you send?

[mypokemon.json](https://github.com/user-attachments/files/17465984/mypokemon.json)

[mainpokemon.json](https://github.com/user-attachments/files/17465986/mainpokemon.json)

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/user-attachments/files/17522371/mypokemon.json)
@JerryLan123 Here you go ! - Just replace the mypokemon.json file with this one and you should be good to go :) - Let me know if any issues persist !

**Comment by JerryLan123** [comment]
@Unlucky-Life 

I went ahead and replaced it but now this is popping up.


Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.6.1-x86_64-i386-64bit

Add-on Startup Failed
The following add-ons failed to load: ⁨
[Ankimon by Unlucky-life](https://ankiweb.net/shared/info/1908235722)⁩
They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available.
You can use the Copy Debug Info button to get information that you can paste in a report to the add-on author.
For add-ons that don't have an update available, you can disable or delete the add-on to prevent this message from appearing.

**Comment by Unlucky-Life** [comment]
could you copy the debug information here ?

**Comment by Unlucky-Life** [comment]
[mypokemon.json](https://github.com/user-attachments/files/17525444/mypokemon.json)
ok i think i fixed the issue ! - I made a 2-3 errors when missing a comma , and a "" - now it should work ! - Try to replace your mypokemon.json again :)!

**Comment by JerryLan123** [comment]
@Unlucky-Life It works perfectly now, thank you so much :D!!! Sorry I hadn't seen your other message regarding the debug info

**Comment by Unlucky-Life** [comment]
Hey man no worries :) have fun !
