### ISSUE TITLE
Issue with pokemon not fighting back

### ISSUE THREAD

**Issue by ghostface29** [Unlucky-Life/ankimon#214]
While doing Anki, every other card my pokemon does an attack however the wild pokemon does nothing. Is this how it is programed? or do I need to change a setting?

**Comment by Unlucky-Life** [comment]
Yea no this is correct (every two cards, you main pokemon uses a random attack). To lose hp from the enemy pokemon you need to go to settings, and set dmg in reviewer to true.
Hope that helps !

**Comment by ghostface29** [comment]
Thank you for your reply, where do I go to do that? I have a mac. I do not see settings

**Comment by Unlucky-Life** [comment]
This is really easy - Navigate in Anki to - Addons - Click on Ankimon - and then settings :)

**Comment by ghostface29** [comment]
thanks, got it
