### ISSUE TITLE
Trouble while switching main pokemon

### ISSUE THREAD

**Issue by Anthony913x** [Unlucky-Life/ankimon#219]
When I want to switch my main pokemon, it will show "following error occurred while opening window: integer division or odulo by zero"

**Comment by Unlucky-Life** [comment]
@Anthony913x This is an easy fix ! 

You need to download the sprites from:
https://github.com/Unlucky-Life/ankimon/blob/main/missing_back_sprites/missing_back_sprites.zip 

Then you can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window. Click on the View Files button, and a folder will pop up. 

From there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded (unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)
