### ISSUE TITLE
Add an option to automatically catch or defeat Pokemon

### ISSUE THREAD

**Issue by cocowash** [Unlucky-Life/ankimon#224]
Hi, I love the addon, thanks for sharing this project with the community. 
I have a small petition, and it is to add an option to automatize the catch or defeat when this feature is enabled.
 I like the ambience that the addon gives to study, but at the same time I feel that changing the window to decide what happens to the fainted Pokemon kind of kills the tempo of the study session. I really like the gamification that brings to anki, but I would prefer that it could behave completely as an idle game that doesn't require my attention to make progress.

**Comment by Unlucky-Life** [comment]
you could download the newest stable ankimon version:

The last stable Ankimon Version: https://github.com/Unlucky-Life/ankimon/releases/tag/1.288 - it allows you to go to Tools => Ankimon by Unlucky Life => Settings => and there you can change automation for catching and defeating a pokemon (meaning once pokemon has 0 hp, next "round" = 2 cards => based on your setting, the pokemon will be automatically caught or defeated)
