### ISSUE TITLE
Error message after trying to switch main Pokemon

### ISSUE THREAD

**Issue by sdohai** [Unlucky-Life/ankimon#225]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.6.1-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/haileygerbs/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 2970, in <lambda>
    choose_pokemon_button.clicked.connect(lambda state, name=pokemon_name, nickname=pokemon_nickname, level=pokemon_level, id=pokemon_id, ability=pokemon_ability, type=pokemon_type, detail_stats=pokemon_stats, attacks=pokemon_attacks, hp=pokemon_hp, base_experience=mainpokemon_base_experience, growth_rate=pokemon_growth_rate, ev=pokemon_ev, iv=pokemon_iv, gender=pokemon_gender: MainPokemon(name, nickname, level, id, ability, type, detail_stats, attacks, hp, base_experience, growth_rate, ev, iv, gender))
  File "/Users/haileygerbs/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 3641, in MainPokemon
    new_pokemon() #new pokemon if you change your pokemon
  File "/Users/haileygerbs/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1857, in new_pokemon
    test_window.display_first_encounter()
  File "/Users/haileygerbs/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 5833, in display_first_encounter
    battle_widget = self.pokemon_display_first_encounter()
  File "/Users/haileygerbs/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 5500, in pokemon_display_first_encounter
    image_label, msg_font = window_show()
  File "/Users/haileygerbs/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 5414, in window_show
    new_height2 = (original_height2 * max_width) // original_width2
ZeroDivisionError: integer division or modulo by zero

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Ankimon by Unlucky-life ['1908235722', 2024-05-16T10:07, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T20:19, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T06:59, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
Spell Checker ['369581638', 2023-10-11T08:47, 'None', '']

===IDs of active AnkiWeb add-ons===
1210908941 1722658993 1771074083 1908235722 369581638

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Unlucky-Life** [comment]
Hi @sdohai !
This is an easy fix:
ou need to download the sprites from:
https://github.com/Unlucky-Life/ankimon/blob/main/missing_back_sprites/missing_back_sprites.zip

Then you can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window. Click on the View Files button, and a folder will pop up.

From there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded (unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)

**Comment by Unlucky-Life** [comment]
if the issue persists, let me know !
