### ISSUE TITLE
Can't Open Ankimon Window

### ISSUE THREAD

**Issue by jliu1002** [Unlucky-Life/ankimon#226]
Hi,

When I click "Open Ankimon Window," the following error message shows up: "Following Error occured when opening window: integer division or modulo by zero." I have attached a screenshot of the message. Thank you!
<img width="252" alt="Screenshot 2024-11-16 at 12 33 10 PM" src="https://github.com/user-attachments/assets/99240137-1b9a-455a-964d-f29713220ed1">

**Comment by Unlucky-Life** [comment]
This means you are missing some back sprites which you can manually install by going to
https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
Download the missing sprites from this folder and place them in 'back_default' under 'sprites / user_files'  in the Ankimon Addon Folder

**Comment by Unlucky-Life** [comment]
Hope that helps !

**Comment by jliu1002** [comment]
It's resolved now thank you so much!
