### ISSUE TITLE
Problem with Legendary pokemons.

### ISSUE THREAD

**Issue by Zynx07** [Unlucky-Life/ankimon#227]
When I try to open the ankimon window after picking Yveltal or Zygarde, it keeps saying error for some reason and I can't open it at all, they keep fighting when I answer questions but the ankimon window can't be opened when I pick them.
![Uploading WhatsApp Image 2024-11-17 at 00.41.11_d4a0fc14.jpg…]()

**Comment by LeonArthurMoegelin** [comment]
Hi @Zynx07 !
This is an easy fix:
You need to download the sprites from:
https://github.com/Unlucky-Life/ankimon/blob/main/missing_back_sprites/missing_back_sprites.zip

Then you can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window. Click on the View Files button, and a folder will pop up.

From there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded (unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)

**Comment by Unlucky-Life** [comment]
Hi @sdohai !
This is an easy fix:
You need to download the sprites from:
https://github.com/Unlucky-Life/ankimon/blob/main/missing_back_sprites/missing_back_sprites.zip

Then you can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window. Click on the View Files button, and a folder will pop up.

From there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded (unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)

**Comment by Unlucky-Life** [comment]
if the issue persists, let me know !

**Comment by Zynx07** [comment]
Thank you so much for you help :D
