### ISSUE TITLE
Evolving Pokemon Bug

### ISSUE THREAD

**Issue by kttk01** [Unlucky-Life/ankimon#228]
Whenever I level up any Pokemon to evolve it and have 2 of the same species in my collection, it will also evolve the other Pokemon in my collection even though I wasn't using that one. It will evolve the other one even though it hasn't met the EXP level requirement.

Like many others, I am trying to create a living Pokedex by generation so I tend to have duplicates of the same Pokemon.

The following images are examples of both Pokemon evolving even though I only trained one. (One meeting the EXP level requirement and the other one not)

![Mankey](https://github.com/user-attachments/assets/e35fcdee-a1f2-4025-aac9-68dbd5fa7c89)
![Persian](https://github.com/user-attachments/assets/93c8ba20-2944-485a-8903-3ec3c2fe0eff)
![Tentacool](https://github.com/user-attachments/assets/23712fbf-02f3-4f49-af53-94f4727778dd)

**Comment by Unlucky-Life** [comment]
@kttk01 sadly this is a bug im currently working on aswell. I hope next update fixes this better !
