### ISSUE TITLE
Evolving pokemon sun stone bug.

### ISSUE THREAD

**Issue by zdanielp** [Unlucky-Life/ankimon#230]
Unable to evolve Gloom to Bellossom using Sun stone

![imagen](https://github.com/user-attachments/assets/7f821f12-8cd0-4d59-b15f-a016dbf27ecd)
![imagen](https://github.com/user-attachments/assets/86fe7093-b483-472e-bd10-870210c1e7b8)

**Comment by Unlucky-Life** [comment]
Sadly the currently is an error with alot of item based evolutions
