### ISSUE TITLE
Ankimon error

### ISSUE THREAD

**Issue by ZAMZAM997** [Unlucky-Life/ankimon#231]
I am getting an integer division or modulo by zero error when i tried to open Ankimon window

**Comment by ZAMZAM997** [comment]
Anki 24.06.2 (33a92379)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.18363

Traceback (most recent call last):
  File "C:\Users\dell\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1051, in <lambda>
    QTimer.singleShot(period, lambda: lab.hide())
RuntimeError: wrapped C/C++ object of type CustomLabel has been deleted

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Anki Leaderboard - Compete with friends to boost motivation Fork by Shige ['175794613', 2024-11-16T20:25, 'None', mod]
Ankimon by Unlucky-life ['1908235722', 2024-05-16T16:07, 'None', '']
Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T23:11, 'None', mod]
Collapsible Fields ['1896168623', 2021-08-28T22:45, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-03-01T02:22, 'v1.0.2', mod]
Customize Keyboard Shortcuts ['24411424 22-35-18-218', 2022-06-29T07:13, 'None', '']
Free Weekend - or Any Other Day ['742185195', 2020-04-10T11:57, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T07:15, 'None', '']
Pop-up Dictionary beta ['153625306', 2019-03-23T17:32, 'None', '']
Progress Bar ['2091361802', 2019-03-03T03:27, 'None', '']
Resize images in editor ['1103084694', 2021-07-19T07:35, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
See Previous Card Ratings in Reviewer ['1906641654', 2021-08-19T22:32, 'None', '']

===IDs of active AnkiWeb add-ons===
1103084694 1374772155 153625306 175794613 1771074083 1896168623 1898790263 1906641654 1908235722 2091361802 742185195 831846358

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['popup_dictionary', 0, 'None', mod]
'' ['put_ALL_due_learning_cards_first', 0, 'None', '']
AJT Merge Notes  Merge and Duplicate notes ['1425504015', 2024-09-17T20:35, 'None', mod]
Add Hyperlink ['318752047', 2023-06-18T12:39, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T11:10, 'None', mod]
Advanced Browser ['874215009', 2024-10-27T15:20, 'None', '']
Advanced Card Styles ['1625103157', 2021-12-28T18:49, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-10-21T15:29, 'None', mod]
Anki Habitica for 21 ['1758045507', 2024-09-03T11:47, 'None', '']
Anki Killstreaks - Reward Medals for Correct Answers Fixed by Shige ['1562475180', 2024-09-19T19:43, 'None', mod]
Anki Killstreaks ['579111794', 2021-12-15T16:20, 'None', '']
Anki Simulator ['817108664', 2023-11-06T18:26, 'None', '']
AnkiConnect ['2055492159', 2024-11-07T02:34, 'None', mod]
AnkiCraft ['368161874', 2024-08-22T10:46, 'None', '']
AnkiHub ['1322529746', 2024-11-12T18:38, 'None', mod]
Answer Confirmation for 21 ['1354051622', 2019-04-04T12:54, 'None', '']
Answer visual  auditory  custom text reinforcement ['976516370', 2024-03-08T10:04, 'None', mod]
Audiovisual Feedback ['231569866', 2023-07-09T04:34, '0.8', mod]
Auto Sync ['501542723', 2023-11-20T17:14, 'None', '']
Batch Editing ['291119185', 2023-10-26T01:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T17:25, 'None', mod]
Bionic Reading ['649714433', 2023-10-26T22:24, 'None', mod]
Browser Resizer ['1435775540', 2023-11-11T18:16, 'None', '']
Button Colours Good Again ['2494384865', 2022-09-27T11:18, 'None', '']
Calculate New Cards To Do ['2014569756', 2022-05-19T06:38, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-30T23:58, 'None', '']
Closet For Anki ['272311064', 2022-08-12T09:27, 'None', '']
Cloze Overlapper for Anki 21 ['109531687', 2021-01-12T04:12, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T16:06, 'None', '']
Convert Subdecks to Tag Hierarchy ['1172858842', 2023-02-07T19:15, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T12:50, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T02:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T10:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-11-16T11:23, '6.21', mod]
Exam Notifier ['236593452', 2023-01-19T18:12, 'None', '']
Export Single Tag For Sharing ['960563361', 2022-04-10T22:30, 'None', '']
Extended Card Stats During Review ['1008566916', 2024-02-26T20:07, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T17:58, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T12:47, 'None', '']
Field AutoComplete ['511710206', 2024-07-20T15:07, 'None', mod]
Google Doc Decks Remote Decks ['924929499', 2024-05-05T02:58, 'None', '']
Google Translate ['1536291224', 2024-10-21T15:10, 'None', '']
High Yield Tags ['1918380616', 2023-01-10T20:14, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T20:17, 'None', '']
Hint Hotkeys ['1844908621', 2023-04-14T15:13, 'None', '']
Hitmarkers ['1776869150', 2024-02-24T12:19, 'None', '']
Image Editor ['307397307', 2022-09-08T05:09, 'None', '']
Image Style Editor ['1593969147', 2021-12-17T08:01, 'None', mod]
ImageResizer ['1214357311', 2023-12-03T02:58, 'None', '']
Learning Step and Review Interval Retention ['1949865265', 2024-01-06T18:48, 'None', '']
Leech Toolkit ['368380974', 2024-04-01T18:02, 'None', '']
Load Balanced Scheduler ['208879074', 2019-07-24T03:37, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T19:00, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-19T23:49, 'None', '']
More Overview Stats 21 ['738807903', 2024-08-22T10:14, 'None', mod]
New Cards Counter ['635082046', 2022-04-20T21:37, 'None', '']
PDF Exporter ['1442112168', 2022-11-16T21:23, 'None', '']
Picmonic Anki Add-On ['40737180', 2024-01-24T17:02, 'None', mod]
Pokemanki Gold - Raising Pokemon with Anki Customized by Shige ['1677779223', 2024-11-16T22:03, 'None', '']
Pokemanki Silver - Raising Pokemon with Anki Fork by Shige ['212957849', 2024-04-23T00:28, 'None', '']
Pokmanki ['1041307953', 2023-12-02T15:32, 'None', '']
Pop-up Wikipedia Beta ['395343016', 2020-01-09T04:58, 'None', '']
Postpone cards review ['1152543397', 2023-04-15T03:29, 'None', '']
Progress Bar original ['1685464019', 2022-07-28T06:24, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T13:59, 'None', '']
Puppy Reinforcement ['puppy_reinforcement', 2020-02-05T08:16, 'None', mod]
Quick Colour Changing ['2491935955', 2023-10-19T04:15, 'None', mod]
Quizlet to Anki 21 Importer with audio support ['1362209126', 2024-11-15T10:33, 'None', '']
ReColor ['688199788', 2024-03-03T02:45, '3.0', mod]
Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-20T05:40, 'None', '']
Remove Duplicate Cards ['95590040', 2024-09-29T16:56, 'None', '']
Reset Ease ['947935257', 2023-11-12T02:22, 'None', '']
Runescape-Gamification fork ['1490041567', 2024-02-29T13:38, 'None', '']
SMART SPACEBAR automatic ease scoring ['490202012', 2019-08-07T21:52, 'None', '']
Searching PDF Reading  Note-Taking in Add Dialog - Qt6 port ['572933442', 2024-04-02T17:18, 'None', mod]
Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2022-08-15T08:22, 'None', mod]
Special Fields ['1102281552', 2024-10-26T16:51, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T12:24, 'None', '']
Spell Checker with Custom Dictionaries ['390813456', 2022-11-26T17:38, 'None', mod]
Stats Plus ['1009670238', 2021-03-04T13:23, 'None', '']
Straight Reward ['957961234', 2023-11-01T15:11, 'None', '']
Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T20:52, 'None', mod]
Symbols As You Type ['2040501954', 2024-01-20T06:42, 'None', '']
Symbols ['1461102936', 2024-02-10T17:53, 'None', mod]
The Human Insight Project THIAI - AI-Powered Medical Knowledge Companion ['187810340', 2023-11-09T01:53, 'None', '']
The KING of Button Add-ons ['374005964', 2024-09-23T13:14, 'None', mod]
The KING of Study Timers ['907028815', 2022-04-20T19:14, 'None', mod]
True Retention ['613684242', 2017-11-19T21:43, 'None', '']
True Retention by Card Maturity ['923360400', 2017-08-29T20:00, 'None', '']
UpToDate Addon ['utd_anki_addon', 2023-05-08T16:16, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T20:28, 'None', mod]
Weekends and Holidays ['1992008104', 2022-12-20T02:24, 'None', mod]
Wrapper meta-addon ['396502676', 2024-06-10T11:00, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T17:22, 'None', '']
rebuildempty some or all filtered decks ['104518886', 2023-05-16T23:33, 'None', '']
uworld_qid_to_anki_search ['607963104', 2023-01-18T22:20, 'None', '']
when is next learning card due today due ['563204849', 2021-12-06T16:06, 'None', mod]

**Comment by 12zzzaaa** [comment]
pls help solve this issue I just lost a larvitar bc I dont have the catch option I cant even see my Pokemon how ever will I do my Anki now???? if I fail all my finals its bc of this bug

**Comment by Unlucky-Life** [comment]
This is an easy fix ! @ZAMZAM997 @12zzzaaa  @439qi @anbzerc 

https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
=> You can download the zip file in here and unpack the zip file on your system with right click (best to have an application like 7zip for this).

(unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)

You can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window.

Click on the View Files button, and a folder will pop up. 
from there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded

Restart Anki and you should be good to go !

**Comment by Unlucky-Life** [comment]
> pls help solve this issue I just lost a larvitar bc I dont have the catch option I cant even see my Pokemon how ever will I do my Anki now???? if I fail all my finals its bc of this bug

@12zzzaaa 

No worries, got you ! Just send me your mypokemon.json file and mainpokemon.json file and i can inject the lavitar for you, just let me know what level it was ;)!

**Comment by 12zzzaaa** [comment]
Appreciate the help boss

**Comment by ItsStolas** [comment]
Locally, I added a fallback to the '?' sprite @Unlucky-Life.

`if not pixmap2.load(str(pkmnimage_path2)):
 pixmap2.load(str(backdefault / "0.png"))`

**Comment by Unlucky-Life** [comment]
I like it 👀👌
