### ISSUE TITLE
Gen 5 Starters Not Available?

### ISSUE THREAD

**Issue by wjh-iii** [Unlucky-Life/ankimon#233]
Have loved using the extension for several months now. Went to study Anki on a different computer and when selecting a new starter, I swear I clicked G at least 100 times and was never able to come across the Gen 5 starters (Oshawott, Tepig, Snivy)! Took a look at the starter file/Pokémon csv and it looks like they're included in the Pokémon csv but not in the starter file. Have little coding knowledge but is there a reason for this? Just wanna train up an Oshawott :(

Thank you for this add-on and everything yall do to improve it

**Comment by Unlucky-Life** [comment]
@wjh-iii ah damn thats true !

**Comment by Unlucky-Life** [comment]
[starters.json](https://github.com/user-attachments/files/18129426/starters.json)
if you drag and drop this file under Ankimon Folder => addon_files => starters.json you should be able to replace the starters.json with this file.


Then you would need to reset your ankimon by replacing the files mainpokemon.json and mypokemon.json with the reset files in the github repo: https://github.com/Unlucky-Life/ankimon/tree/main/ResetFiles

**Comment by wjh-iii** [comment]
I have my boi as a starter now, appreciate your help!
