### ISSUE TITLE
this error appears for me sometimes when i click on the "easy" button

### ISSUE THREAD

**Issue by Matheus552br** [Unlucky-Life/ankimon#238]
![image](https://github.com/user-attachments/assets/b1143aae-2ab1-4982-bd3f-950e059ae338)

**Comment by Unlucky-Life** [comment]
@Matheus552br hm ok this is weird - can you restard anki and check if this reappears ? Else id recommend checking if there are any addons that might interact here with your buttons aswell as checking if you have already all the needed sprites
