### ISSUE TITLE
Is there any way to import resources instead of downloading them in the add-on

### ISSUE THREAD

**Issue by s1067358196** [Unlucky-Life/ankimon#239]
Hi, I've tried many times to download resources in the add-on, but I always encounter connection timeouts that result in download failures. Is there a way to import resources instead? When I run the program, I sometimes encounter this error while capturing Pokémon. I'm not sure if it's due to an issue with the integrity of the resource files. My anki.exe version is anki-24.11-windows-qt6.
ps: I really appreciate your add-ons making learning so much fun.
![image](https://github.com/user-attachments/assets/347c57bb-f9cf-4b9b-95a0-7d90d99ff6c6)

**Comment by Unlucky-Life** [comment]
Hi @s1067358196 
Ah so  https://github.com/Unlucky-Life/ankimon/releases/tag/1.288 - enables  you to download this build where the sprites are included ! Aswell as the missing sprites you can download under https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites - where you can download the rest of the missing sprites and paste them into the Ankimon folder under => user_files => back_default. I hope that helps !
Thx fot the kind words !
