### ISSUE TITLE
Download stuck/crash/problem after update

### ISSUE THREAD

**Issue by nurkittel** [Unlucky-Life/ankimon#24]
Hi,
for some reasons I wanted to try a full new install with the new update and so I deleted Ankimon. Reinstalled the new version and I had to download the files again. 
Here the Problem begins. For some reasons and I tried a few times it will stop/freeze and won't continue to download. Since it takes a long time to download the additional files I don't know if it's because my MacBook will automatically switch to sleep/display off after a few seconds and because it takes so long I guess the majority of users do this instead of looking at the download progress. 
So I come back and the download does not continue I close Anki and then I get a popup that the program unexpectedly quit. It did not sync as usual if I close Anki. When I reopen a popup appears that Ankimon add-on is broken and was not loaded. So I have to delete and try again. So far no success. 

What can I do? Does reinstalling Anki might help or is the add-on completely independent? Do I need to have Anki on the Front screen all the time until it full downloaded?

**Comment by Unlucky-Life** [comment]
him ok this weird - send the update yesterday to a friend.
I think you need to uninstall the addon - and then wait for the downloads to all go through.

**Comment by Unlucky-Life** [comment]
after installing the new update this window should pop up: 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/e3e7e106-439c-4d9f-8ad0-138a7b708b87)

did this happen with you ?

**Comment by Unlucky-Life** [comment]
because your anki will only open once you closed that window

**Comment by nurkittel** [comment]
It comes up the problem appears after I press Download Files in the Ankimon Menu

**Comment by nurkittel** [comment]
It freezes during Download Files, crashes Anki and when I reopen Anki it notify me at the start that Ankimon is broken and needs to be reinstalled. Maybe its a individual me or Mac problem idk.

**Comment by Unlucky-Life** [comment]
friend tested it on a mac

**Comment by Unlucky-Life** [comment]
hm - maybe try with this version: https://github.com/Unlucky-Life/ankimon/releases/download/1.24/ankimon-1.24-anki21-ankiweb.ankiaddon

**Comment by Unlucky-Life** [comment]
basically:
1. delete ankimon (before you do this, make sure to copy the mainpokemon.json, mypokemon.json, badges.json and items.json to a different location outside of the ankimon folder
2. reinstall ankimon
3. then go to "download resources"

**Comment by Unlucky-Life** [comment]
- if it works let me know

**Comment by nurkittel** [comment]
Will do, if it works I will try to reproduce the error and tell you.

**Comment by Unlucky-Life** [comment]
https://github.com/Unlucky-Life/ankimon/issues/24#issuecomment-2002489380
=> if its not letting you go to hibernate/sleep mode in no fullscreen - it a good sign
- because the download process seems then to be running in the background

=> the hibernation/sleep mode good kill the download process and then lead to the crashed

=> because it gives the addon the feeling you have downloaded all files - but then crashes because it doesnt seem to find them / they are corrupted.

=> and canceling the download process does actually shutdown anki (but i cant tell why tho)

**Comment by nurkittel** [comment]
It's working now, as long as you babysit the download and not letting the laptop go to sleep/... . Pressing download and leaving it alone will cause the error at least in fullscreen 3 times.

**Comment by Unlucky-Life** [comment]
https://we.tl/t-IO3VVf6GxC - here is the complete addon folder if the crashing is still there

**Comment by Unlucky-Life** [comment]
ok thanks for the notice!

**Comment by Unlucky-Life** [comment]
- the infos for mac users should now be displayed for other users
