### ISSUE TITLE
New Main Pokemon glitch

### ISSUE THREAD

**Issue by bkm1171** [Unlucky-Life/ankimon#244]
crashes when i try to select a new main pokemon. debug info: 
Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "/Users/brannonmaravich/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 2807, in <lambda>
    choose_pokemon_button.clicked.connect(lambda state, name=pokemon_name, nickname=pokemon_nickname, level=pokemon_level, id=pokemon_id, ability=pokemon_ability, type=pokemon_type, detail_stats=pokemon_stats, attacks=pokemon_attacks, hp=pokemon_hp, base_experience=pokemon_base_experience, growth_rate=pokemon_growth_rate, ev=pokemon_ev, iv=pokemon_iv, gender=pokemon_gender: MainPokemon(name, nickname, level, id, ability, type, detail_stats, attacks, hp, base_experience, growth_rate, ev, iv, gender))
  File "/Users/brannonmaravich/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 3641, in MainPokemon
    new_pokemon() #new pokemon if you change your pokemon
  File "/Users/brannonmaravich/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 1857, in new_pokemon
    test_window.display_first_encounter()
  File "/Users/brannonmaravich/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 5833, in display_first_encounter
    battle_widget = self.pokemon_display_first_encounter()
  File "/Users/brannonmaravich/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 5500, in pokemon_display_first_encounter
    image_label, msg_font = window_show()
  File "/Users/brannonmaravich/Library/Application Support/Anki2/addons21/1908235722/__init__.py", line 5414, in window_show
    new_height2 = (original_height2 * max_width) // original_width2
ZeroDivisionError: integer division or modulo by zero

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T09:24, 'None', mod]
AnkiHub ['1322529746', 2024-12-23T13:50, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-16T10:07, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1322529746 1771074083 1908235722

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Unlucky-Life** [comment]
This is an easy fix ! @bkm1171 

https://github.com/Unlucky-Life/ankimon/tree/main/missing_back_sprites
=> You can download the zip file in here and unpack the zip file on your system with right click (best to have an application like 7zip for this).

(unzip a file = decompressing a zip file to a normal folder - works by right clicking and selecting unzip file)

You can access the add-ons folder by going to the Tools>Add-ons then click on "Ankimon (by Unlucky-life)" menu item in the main Anki window.

Click on the View Files button, and a folder will pop up.
from there you can go to => user_files => back_default
in that folder you just copy the files from the zip file that you have downloaded

Restart Anki and you should be good to go !

**Comment by bkm1171** [comment]
that worked perfectly!! I didn't think I was savvy enough to follow those instructions but I made it happen and feel like a wizard. Thank you for the fast response!!
