### ISSUE TITLE
The Japanese font size is too big where the Axolotl font is applied.

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#27]
The Japanese characters are unusually large.
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/2a3c31d0-579c-4dae-ac40-e1baf0170690)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/764d34fc-3082-4a0f-9629-ac4dfcadc6c2)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/f3e0516a-f0b5-4eb9-88f4-3e9e34aeeca4)

The topic shifts, but a reproduction of the Japanese font used in Pokémon for the Game Boy is available. It only supports hiragana, katakana, Latin (English), and some symbols, but feel free to check it out if you're interested.

![Pokemon GB Font list](https://jikkyofont.com/wp-content/uploads/2021/08/jikkyou2-2-1536x864.png)

## Reference pages for the Japanese font
[The "Pokemon GB Font" page](https://www.fontspace.com/pokemon-gb-font-f9621)

**Comment by Unlucky-Life** [comment]
do you know if that font is free to use ?

**Comment by Unlucky-Life** [comment]
the issue with that font is that Hiragana and the Katakana Files are seperate => this issue being that those files are seperated and the file that uses the descriptions for the pokemon is merged in one category category ("language 1 = hiragana and katakana)

i would need a file that merges these two alphabets

**Comment by Foxy-null** [comment]
Actually, there's another version of a Japanese font that merges both katakana and hiragana in one font file. However, since the license was not clearly stated, I avoided mentioning it. I'll send the distribution page for that font in the comments shortly.

**Comment by Unlucky-Life** [comment]
so i tried those fonts - but somehow they are not loading properly

**Comment by Unlucky-Life** [comment]
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/2e55666b-552a-4b76-b99b-6435721f8397)
ok i may have found the issue.
Can you check if the characters here are corret ? 
(ill change the sizing after)

**Comment by Unlucky-Life** [comment]
here is a good font you can use: license: Freeware, Non-Commercial
link: https://www.fontspace.com/nineteen-ninety-three-font-f29544
=> for non-commercial, freeware
Nineteen-Ninety-Three-Font by Chequered Ink
- download the file named above - and drag and drop the `NineteenNinetyThree-L1Ay.ttf` file into the `addon_files` folder

- or you can now download the `Early GameBoy.ttf` file from the `github addon_files` folder.
https://github.com/Unlucky-Life/ankimon/blob/5fc1905647a9bcc3adc287e3d959f7afc023ab68/src/Ankimon/addon_files/Early%20GameBoy.ttf

- then download the __init__.py file from the github and replace the one into the ankimon folder
- https://github.com/Unlucky-Life/ankimon/blob/bfcead09bd53103da13a5de5c7ef792cac1a0061/src/Ankimon/__init__.py

This should change the size issue: 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/791bbd25-b4fd-46f5-bf55-7327175a1fed)
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/71b4704a-cb45-4776-87bc-f1bbe27728f1)

**Comment by Unlucky-Life** [comment]
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/e4eddf20-2cc7-4f47-8118-c63e05016c63)
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/3024ca38-944e-4a46-b94d-7a193b7629a6)

**Comment by Foxy-null** [comment]
> ![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/2e55666b-552a-4b76-b99b-6435721f8397)
> 
> ok i may have found the issue.
> 
> Can you check if the characters here are correct ? 
> 
> (ill change the sizing after)

Wow... what a strange way of displaying things. It seems like English was the worst match. I should have tried it in my own environment before recommending it. I'm sorry.

**Comment by Foxy-null** [comment]
> here is a good font you can use: license: Freeware, Non-Commercial
> 
> link: https://www.fontspace.com/nineteen-ninety-three-font-f29544
> 
> => for non-commercial, freeware
> 
> Nineteen-Ninety-Three-Font by Chequered Ink
> 
> - download the file named above - and drag and drop the `NineteenNinetyThree-L1Ay.ttf` file into the `addon_files` folder
> 
> 
> 
> - or you can now download the `Early GameBoy.ttf` file from the `github addon_files` folder.
> 
> https://github.com/Unlucky-Life/ankimon/blob/5fc1905647a9bcc3adc287e3d959f7afc023ab68/src/Ankimon/addon_files/Early%20GameBoy.ttf
> 
> 
> 
> - then download the __init__.py file from the github and replace the one into the ankimon folder
> 
> - https://github.com/Unlucky-Life/ankimon/blob/bfcead09bd53103da13a5de5c7ef792cac1a0061/src/Ankimon/__init__.py
> 
> 
> 
> This should change the size issue: 
> 
> ![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/791bbd25-b4fd-46f5-bf55-7327175a1fed)
> 
> ![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/71b4704a-cb45-4776-87bc-f1bbe27728f1)
> 
> 

Thank you for the alternative suggestion. I'll try it out right away. If I find another promising font, I'll test it in my own environment before letting you know next time!

**Comment by Foxy-null** [comment]
Sorry for the late reply. This works really nicely! Thank you for your continuous support!

![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/5ed12766-f665-430c-a1d4-d029dd13ce99)

**Comment by Foxy-null** [comment]
> ok i may have found the issue. Can you check if the characters here are correct ? (ill change the sizing after)

The lowercase alphabets were corrupted, but this was fixed by changing the font to "Western". I also made some changes to make them more similar to certain authentic Pokémon.

I'll create a pull request for these changes; could you please review it?

- [x] Change Japanese font
    - Bug fix for displaying voiced and semi-voiced Japanese characters in the Pokédex description for Pokémon names.
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/8ad6ec32-b0c8-48cc-901f-6b10a42a1a28)

- [x] Switched the Pokémon gender display to use male and female symbols
     - For Pokémon without gender, no symbols are displayed.
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/76f38f47-585b-4387-9381-eb9501876ce7)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/a5433bbd-2471-498f-892c-89ce9f7d69e4)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/5c410eed-368a-41e5-a2a8-b47df758e361)

- [x] Created a Japanese versions of the text "A wild 'pokemon' has appeared" text.
    - It seems that even though I used "\n", the line break wasn't applied as intended in the middle of the sentence.
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/7316c826-0f46-4456-b827-6332b7ed39f8)

Thank you.

**Comment by Unlucky-Life** [comment]
Hey man looks great ill take a look !

**Comment by Unlucky-Life** [comment]
The Gender Symbol thing, when i checked it out back then - seemed to not work with the axolotl => maybe with the new font it should work !

**Comment by Unlucky-Life** [comment]
The \n is not applied in pyqt qlabels sadly

**Comment by Foxy-null** [comment]
> The Gender Symbol thing, when i checked it out back then - seemed to not work with the axolotl => maybe with the new font it should work !

Hey, Could you please explain how the gender symbol doesn't function with the Axolotl font? It seems to work fine in my Windows 11 environment.

![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/75a42ce4-a65d-4ec5-a6f8-17927df2004f)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/b7794e09-ca6a-4e73-86d6-0798ab12b811)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/383d7d99-eae9-48ec-8b68-9ee40a24938a)
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/04097aee-5656-4153-a493-8cd4630a64b5)

**Comment by Unlucky-Life** [comment]
Sadly i cant remember what exactly didnt work :/
