### ISSUE TITLE
The battle sound plays even when both the sound and battle_sound options are disabled.

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#28]

**Comment by Foxy-null** [comment]
Disabling sound effects in the options and restarting did not make them disappear, but after continuing to review the cards for several hours, the sound effects were gone without me noticing. It's strange, but until someone else with the same symptoms comes along, I'll close this issue.

**Comment by Unlucky-Life** [comment]
Seems like i found the issue ! I was missing a config check for battle cries: 

Please redownload this file: https://github.com/Unlucky-Life/ankimon/blob/b66509a8004db069cfce4ef826ca7e031ee265d7/src/Ankimon/__init__.py

And overwrite the __init__.py file in the ankimon addon folder.
I hope this should solve the issue.

**Comment by Foxy-null** [comment]
Thank you so much. I'll try that later when I get home!
