### ISSUE TITLE
'NoneType' object has no attribute 'mapToGlobal'

### ISSUE THREAD

**Issue by liu1234567891011** [Unlucky-Life/ankimon#29]
hey anytime i try to evolve my charmander from a level 6 to 7, i get an error and the ankimon add on stops working.

Anki 23.12.1 (1a1d4d54) (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.5.1-x86_64-i386-64bit

Traceback (most recent call last):
File "/Users/liu/Library/Application Support/Anki2/addons21/1908235722/init.py", line 1230, in kill_pokemon
mainpokemon_level = save_main_pokemon_progress(mainpokemon_path, mainpokemon_level, mainpokemon_name, mainpokemon_base_experience, mainpokemon_growth_rate, exp)
File "/Users/liu/Library/Application Support/Anki2/addons21/1908235722/init.py", line 1523, in save_main_pokemon_progress
tooltipWithColour(msg, color)
File "/Users/liu/Library/Application Support/Anki2/addons21/1908235722/init.py", line 1088, in tooltipWithColour
x = aw.mapToGlobal(QPoint(x + round(aw.width() / 2), 0)).x()
AttributeError: 'NoneType' object has no attribute 'mapToGlobal'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T12:01, 'None', mod]
Add Hyperlink ['318752047', 2023-06-18T07:39, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T06:10, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T10:34, 'None', '']
Anki Killstreaks - Reward Medals for Correct Answers - Fixed by Shige ['1562475180', 2024-03-14T06:46, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T12:26, 'None', '']
AnkiArcade ['AnkiArcade', 0, 'None', mod]
AnkiCraft ['368161874', 2024-03-15T00:07, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-03-17T10:39, 'None', '']
Answer Confirmation for 21 ['1354051622', 2019-04-04T08:54, 'None', '']
Audiovisual Feedback ['231569866', 2023-07-08T23:34, '0.8', mod]
Auto Sync ['501542723', 2023-11-20T11:14, 'None', '']
Batch Editing ['291119185', 2023-10-25T20:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T11:25, 'None', mod]
Browser Resizer ['1435775540', 2023-11-11T12:16, 'None', '']
Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T17:11, 'None', mod]
Button Colours Good Again ['2494384865', 2022-09-27T06:18, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-30T17:58, 'None', '']
Collapsible Fields ['1896168623', 2021-08-28T17:45, 'None', '']
Colorful Tags Hierarchical Tags ['594329229', 2022-09-15T11:06, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2022-08-03T00:02, 'v0.7.0-beta', '']
Convert Subdecks to Tag Hierarchy ['1172858842', 2023-02-07T13:15, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T21:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424 22-35-18-218', 2022-06-29T02:13, 'None', '']
Customize Keyboard Shortcuts ['24411424', 2023-11-01T05:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T02:19, '6.18', mod]
Extended Card Stats During Review ['1008566916', 2024-02-26T14:07, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T11:58, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
Free Weekend - or Any Other Day ['742185195', 2020-04-10T07:57, 'None', mod]
High Yield Tags ['1918380616', 2023-01-10T14:14, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T15:17, 'None', '']
Hint Hotkeys ['1844908621', 2023-04-14T10:13, 'None', '']
Hitmarkers ['1776869150', 2024-02-24T06:19, 'None', '']
Image Editor ['307397307', 2022-09-08T00:09, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Image Style Editor ['1593969147', 2021-12-17T02:01, 'None', mod]
ImageResizer ['1214357311', 2023-12-02T20:58, 'None', '']
Learning Step and Review Interval Retention ['1949865265', 2024-01-06T12:48, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T14:00, 'None', '']
More Decks Stats and Time Left ['1556734708', 2023-09-24T10:08, 'None', '']
More Overview Stats 21 ['738807903', 2021-07-30T15:13, 'None', mod]
Picmonic Anki Add-On ['40737180', 2024-01-24T11:02, 'None', mod]
Progress Bar ['2091361802', 2019-03-02T21:27, 'None', '']
Progress Bar original ['1685464019', 2022-07-28T01:24, 'None', '']
Progress bar Fixed for Anki 23 by Shige ['1708250053', 2024-01-13T10:05, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T07:59, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-18T23:15, 'None', mod]
Reset Ease ['947935257', 2023-11-11T20:22, 'None', '']
Resize images in editor ['1103084694', 2021-07-19T02:35, 'None', mod]
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
SMART SPACEBAR automatic ease scoring ['490202012', 2019-08-07T16:52, 'None', '']
Special Fields ['1102281552', 2023-11-01T12:37, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T06:24, 'None', '']
Straight Reward ['957961234', 2023-11-01T10:11, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T00:42, 'None', '']
Symbols ['1461102936', 2024-02-10T11:53, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-01-27T05:19, 'None', mod]
True Retention ['613684242', 2017-11-19T15:43, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T14:28, 'None', mod]
Wrapper meta-addon ['396502676', 2023-07-22T08:05, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T12:22, 'None', '']
when is next learning card due today due ['563204849', 2021-12-06T10:06, 'None', mod]

===IDs of active AnkiWeb add-ons===
1008566916 1046608507 1052724801 1102281552 1103084694 1135507717 1172858842 1210908941 1214357311 1354051622 1374772155 1435775540 1461102936 1556734708 1562475180 1593969147 1685464019 1708250053 1722658993 1739176371 1771074083 1776869150 1844908621 1896168623 1898790263 1908235722 1918380616 1949865265 2040501954 2091361802 225180905 231569866 24411424 2491935955 2494384865 291119185 295889520 307397307 318752047 368161874 374005964 385888438 396502676 40737180 46611790 490202012 501542723 561945101 563204849 594329229 613684242 738807903 742185195 744725736 817108664 831846358 864545277 874215009 947935257 957961234

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['popup_dictionary', 0, 'None', mod]
'' ['put_ALL_due_learning_cards_first', 0, 'None', '']
Anki Habitica for 21 ['1758045507', 2023-12-16T07:33, 'None', '']
Anki Zoom ['538879081', 2020-04-03T20:20, 'v1.1.3', mod]
Cloze Overlapper for Anki 21 ['109531687', 2021-01-11T22:12, 'None', '']
Load Balanced Scheduler ['208879074', 2019-07-23T22:37, 'None', '']
Placeholder- Pomodoro-like Study Timer ['907028815', 2022-03-04T11:59, 'None', '']
Puppy Reinforcement ['puppy_reinforcement', 2020-02-05T02:16, 'None', mod]
Rebuild All Empty All for Anki 21 ['1810938259', 2018-07-20T00:40, 'None', '']
Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T14:52, 'None', mod]
Zoom 21 ['1846592880', 2020-01-12T12:26, 'None', mod]

**Comment by Unlucky-Life** [comment]
ok thanks for the bug report ! this is awesome, because now i can identify the issue for sure!

**Comment by Unlucky-Life** [comment]
ok might have a fix now. Please redownload this file: https://github.com/Unlucky-Life/ankimon/blob/b66509a8004db069cfce4ef826ca7e031ee265d7/src/Ankimon/__init__.py

And overwrite the __init__.py file in the ankimon addon folder.
I hope this should solve the issue.
