### ISSUE TITLE
File collection incomplete error persists despite downloading all files

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#3]
## What I tried
☆ means I did that method on both 23.12.1 and 24.04rc1
- ☆ Disabled all other add-ons
- ☆ Changed language to English
- Used Anki beta
- ☆ Reinstalled the add-on
- ☆ Downloaded 'Download Badges and Item Sprites' 3 times

![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/39a9e19a-3f51-4a24-9c6b-ca6f95d220aa)

## Environment

OS: Windows 10 22H2
Anki: 23.12.1, 24.04rc1

**Comment by Unlucky-Life** [comment]
ok thats weird ! I will go check that out later today and try to patch that error !

**Comment by Unlucky-Life** [comment]
could you go in to your ankimon files and check under: "pokemon_sprites" if there is a folder for items and badges => if so can you check if there are the sprites inside ?

**Comment by Foxy-null** [comment]
Thank you for the quick reply!
Yes, I have checked that those folders already exist.
`badges` folder: 0.97 MB (67 png files)
`items` folder: 892 KB (336 png files)

Screenshot:
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/8557830b-6f6f-41cd-9bec-19429f984370)

**Comment by Unlucky-Life** [comment]
ok, did you also download through the "Download Database Files" ?

Please check by going into the main addon folder "1908235722" and check for files like "moves.json" "learnsets.json" "pokedex.json" and "pokeapi_db.json". If they are missing download the files through the above named button: "Download Database Files" and the message should go away. The error message i build was just turned around - if ur missing database file it accidentally said missing "badges and item sprites" my bad :D

**Comment by Unlucky-Life** [comment]
If that wont work let me know !

**Comment by Foxy-null** [comment]
It seems that only the "pokeapi_db.json" file was missing. Perhaps there was a glitch in my internet connection while downloading the database file. As you suggested, I tried downloading the database file again, and now it's working perfectly!

# Thank you so much!

Ah, I'm truly happy to see this screen! I feel like my heart could burst with joy!
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/66e74240-22d4-4ee8-a18b-ce639709f8c4)

Thank you again!!!!!!!!
