### ISSUE TITLE
An error occured in reviewer: 'NoneType' object has no attribute 'mapToGlobal'

### ISSUE THREAD

**Issue by Unlucky-Life** [Unlucky-Life/ankimon#31]
ok might have a fix now. Please redownload this file: https://github.com/Unlucky-Life/ankimon/blob/b66509a8004db069cfce4ef826ca7e031ee265d7/src/Ankimon/__init__.py

And overwrite the init.py file in the ankimon addon folder. I hope this should solve the issue.

This fixed the problem thanks!

**Comment by mohayyan** [comment]
it didnt fix the problem no the whole addon crashed
thanks
