### ISSUE TITLE
Mac, my pokemon isn't able to evolve to lvl 10

### ISSUE THREAD

**Issue by Noon1235** [Unlucky-Life/ankimon#34]
this is the error that's showing, "An error occured in reviewer: 'NoneType' object has no attribute 'mapToGlobal'"

never mind i just saw the other reply.
Regardless i really love this add on, thank you.

**Comment by Unlucky-Life** [comment]
@Noon1235 

![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/41d9cafc-71be-434c-a565-0679012af8bd)
