### ISSUE TITLE
More than 8 items do not appear on the item bag screen.

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#39]
Perhaps additional items are not being loaded on the screen.
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/6e0fb1c5-2651-43fb-af95-9f54cad20871)

Full screen view:
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/7efa17f5-f155-464d-96f1-fb2df5eaf275)

Kind regards.

**Comment by nurkittel** [comment]
Same on Mac

**Comment by Unlucky-Life** [comment]
Ah i can see ! Scrollbar integrated in the next update :) 👍

**Comment by nurkittel** [comment]
Thanks for the fix.
On Mac it now opens as an entire new Window (has been different before, similar to the pokemon collection window in front of Anki) and has a small fixed frame, see screenshot. I can not change the size of the frame. But scrolling works. Maybe widen the frame a little.
![Screenshot 2024-03-27 at 11 23 51](https://github.com/Unlucky-Life/ankimon/assets/83577787/8537ec38-f048-4646-af8f-6b98c050750c)

**Comment by nurkittel** [comment]
Awesome! Thanks!

<img width="1440" alt="Screenshot 2024-03-27 at 14 36 21" src="https://github.com/Unlucky-Life/ankimon/assets/83577787/870457f3-419a-4ef0-8235-583af86b0645">
<img width="1440" alt="Screenshot 2024-03-27 at 14 36 05" src="https://github.com/Unlucky-Life/ankimon/assets/83577787/a301cf89-71b3-4859-abf5-8e1dd14433b7">

**Comment by Unlucky-Life** [comment]
does this also fix the issue with where the item and achievement window appears ?

**Comment by nurkittel** [comment]
I use Anki in fullscreen and when I press item or achievements it will open a new full screen window as it should. that's perfect for me. 
When I use Anki 'not in fullscreen' it will open a smaller window frame in front of Anki as it should so I guess it works.

**Comment by Unlucky-Life** [comment]
perfect ! as intended

**Comment by nurkittel** [comment]
Can you apply the same for the Ankimon Window? On Mac u can still see the widges in the background if its in fullscreen. :)
