### ISSUE TITLE
Some Pokémon descriptions are broken.

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#4]
As I was looking through the Pokémon collection, I noticed that the descriptions of some Pokémon are in Japanese. Additionally, instead of pixel art fonts, regular fonts are used, and the text overflows beyond the window width.

### Screenshot
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/2ff7d1b7-35a4-406c-9b4c-619627f55852)

I really love your add-on. I wholeheartedly support its further development!

**Comment by Unlucky-Life** [comment]
Yea i noticed that today aswell - propably there is an issue with the Poke Api DB script - Ill check that the next days and see if i can find a fix ! 

Hey man thanks for the awesome response and beta Testing ! Very helpful and I am very thankful that you like the addon so much !

**Comment by Unlucky-Life** [comment]
(igni here is just the nickname i gave him)

**Comment by Foxy-null** [comment]
Awesome!!!!! Superb job!!!!
