### ISSUE TITLE
Level 100 Pokemon crash anki

### ISSUE THREAD

**Issue by kimo-supremo** [Unlucky-Life/ankimon#40]
here i got zekrom to level 100 and this is what happens when i try to see pokemon details. after i press ok anki crashes

![image](https://github.com/Unlucky-Life/ankimon/assets/70135155/6ed52924-c259-47c7-bd7c-ce3da543d614)

**Comment by Unlucky-Life** [comment]
I found the issue ! Thanks for the post helped alot!
