### ISSUE TITLE
Add on startup failed

### ISSUE THREAD

**Issue by asap-locky** [Unlucky-Life/ankimon#42]
![image](https://github.com/Unlucky-Life/ankimon/assets/150362263/aff88982-3ce1-428c-bed8-985af5dfe996)
Add on startup failed

So the add on startup was successful the first time, but then when I went to download the resources anki timed out and I had to close the app. I tried to re-open it but was getting this error. So I uninstalled and reinstalled, and am still getting this error.

Thank you so much for the creation of this app and for helping me. I'm very excited to use it!

debugging code:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1189, in generate_random_pokemon
    base_experience = search_pokeapi_db_by_id(id, "base_experience")
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2046, in search_pokeapi_db_by_id
    with open(str(pokeapi_db_path), "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files\\data_files\\pokeapi_db.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2099, in <module>
    name, id, level, ability, type, stats, enemy_attacks, base_experience, growth_rate, hp, max_hp, ev, iv, gender, battle_status, battle_stats = generate_random_pokemon()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1221, in generate_random_pokemon
    return generate_random_pokemon()  # Return the result of the recursive call
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1221, in generate_random_pokemon
    return generate_random_pokemon()  # Return the result of the recursive call
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1223, in generate_random_pokemon
    showInfo("Error", "Can't open the JSON File.")
  File "aqt.utils", line 289, in showInfo
TypeError: arguments did not match any overloaded call:
  QMessageBox(parent: Optional[QWidget] = None): argument 1 has unexpected type 'str'
  QMessageBox(icon: QMessageBox.Icon, title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.NoButton, parent: Optional[QWidget] = None, flags: Qt.WindowType = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 1 has unexpected type 'str'

**Comment by Unlucky-Life** [comment]
ok. If when downloading - your Anki crashed - you need to go to your ankimon addon folder => go to "user_files" and then delete the files in "data files" folder=>![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/94ec4ea8-11cb-4ff0-8da5-5dbfc8ac6d20)
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/73edca39-1b1d-4574-87d0-d62920f58e39)
=> then you should be able to redownload the needed resources !

**Comment by asap-locky** [comment]
Hi, thank you so much for your quick response!

so I followed your instructions and tried downloading the resources again. But another error occurred at around 16% downloaded (last time it occurred at 3%) and the program forcibly closed itself.

Do you think this is a bug or instead maybe something wrong with my computer/system? (sorry I don't have much knowledge of computers so just am not sure)

thank you again!
