### ISSUE TITLE
Repeating Error When Switching Main Pokemon

### ISSUE THREAD

**Issue by sunrucong** [Unlucky-Life/ankimon#45]
Hey Unlucky!

When I switch my main Pokemon off of my starter to certain Pokemon and attempt to open up the battle window, I get an error message shown below that doesn't go away (as soon as I close it a duplicate window appears) unless I force quit Anki.

![image](https://github.com/Unlucky-Life/ankimon/assets/161688926/4456d615-217a-499f-8386-15e2292adbf9)

This issue prevents me from catching other Pokemon while having particular non-starter Pokemon as my main Pokemon, so I thought I should let you know!

So far only a Lv. 9 Fletchling has caused the issue, I tried other non-starter Pokemon and they haven't caused any issues.

Please let me know if there's any other information you'd like or need and I'd be glad to try and provide them!

**Comment by Unlucky-Life** [comment]
Hey thanks for the quick notice !
Could you send me your mypokemon.json and mainpokemon.json file here ?
Then ill try to recreate the bug !
Thanks for letting me know !

**Comment by sunrucong** [comment]
Sure thing! Here they are.
[mainpokemon.json](https://github.com/Unlucky-Life/ankimon/files/14819080/mainpokemon.json)
[mypokemon.json](https://github.com/Unlucky-Life/ankimon/files/14819081/mypokemon.json)

**Comment by Unlucky-Life** [comment]
Thank you ! I will try to recreate this bug !

**Comment by Unlucky-Life** [comment]
Hey so i have found the issue ! And this is really weird - but for fletching there a no back images apparently for his back side (Aswell as for his evolution). Ill try to find a sprite and add it if i do find one. 

Enabling .gifs solve this issue at first.

**Comment by Unlucky-Life** [comment]
[back_default.zip](https://github.com/Unlucky-Life/ankimon/files/14850862/back_default.zip)
^ here are zwo sprites you can unzip and place into this folder in your Ankimon Addon Folder:
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/66398cc4-fe79-4a9c-bd32-eac7701f315c)
Once you do so, you should be able to use your Fletchling 👍

**Comment by sunrucong** [comment]
Oh nice, thank you so much!

**Comment by face515** [comment]
The same happens to me with a honedge.

**Comment by Unlucky-Life** [comment]
@face515 copy these images: https://github.com/Unlucky-Life/ankimon/tree/c87e68dd72e51381e6e332625f062585953af009/missing_back_sprites in this folder into
^ here are sprites you can place into this folder in your Ankimon Addon Folder:
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/66398cc4-fe79-4a9c-bd32-eac7701f315c)
Once you do so, you should be able to use your pokemon👍

**Comment by face515** [comment]
Thanks!

**Comment by sunrucong** [comment]
@Unlucky-Life is there a way to download the raw files for the entire folder? I was going to follow @face515 and fill in all the missing back sprites for myself just for future reference but I'm not too familiar with how GitHub works yet
