### ISSUE TITLE
All my pokemon caught always have the same starting moves

### ISSUE THREAD

**Issue by h0zierfan** [Unlucky-Life/ankimon#48]
Each new pokemon caught know "wood hammer, scratch, astonish, and copycat" as their starting moves, which probably isn't intended for pokemon like Lapras

**Comment by h0zierfan** [comment]
ok after catching new pokemon, it seems as the initial pokemon movesets get mixed up based on the last pokemon I didn't catch -- not catching mimikyu led to that moveset for the next four pokemon I caught, but the latest pokemon I caught after defeating a clampearl led to the pokemon knowing clamp, iron defense, watergun, and whirlpool

**Comment by Unlucky-Life** [comment]
Hm this seems weird - was it only with the Ankimon window or only once you opened the Ankimon window right before catching it ?

**Comment by h0zierfan** [comment]
So I tried duplicating the glitch -- whenever I reset anki and catch a new pokemon, the moves are as normal -- however when I catch the next pokemon I encounter, it will have the exact same moves as the last pokemon I caught.

**Comment by h0zierfan** [comment]
My ankimon window was open the entire time also

**Comment by Unlucky-Life** [comment]
hm ok i see - ill check on this myself and see if i can also recreate this error

**Comment by nurkittel** [comment]
Same Issue here. Caught Ditto and Moltres after another and they have the same attacks, doubt its a coincidence.

**Comment by Unlucky-Life** [comment]
Found the issue and should be fixed for the next update !

**Comment by Unlucky-Life** [comment]
@nurkittel @h0zierfan
You could replace those attacks in the pokemon collection with the remember attacks option.
