### ISSUE TITLE
Error that always happens when I update or click to see the answer

### ISSUE THREAD

**Issue by ankiman1** [Unlucky-Life/ankimon#51]
Hi. In the last days i warned an unusual error. All the times that I click "y" to sync anki appear a window that say: 

"**_An error occured in reviewer: unsupported operand type(s) for -=: 'int' and 'NoneType'_** "  

everything seems to be ok, Is it probably an add-on conflict ?

the window also appear when i see the retro of a card ( when i try to answer the card)

**Comment by Unlucky-Life** [comment]
Ok, this seems to be a move error maybe - could please send your mypokemon.json file here and your mainpokemon.json file.
That would help alot recreating this error!

**Comment by Unlucky-Life** [comment]
i found the issue - the issue the move "bide",from your Meditite=>  some moves dont have a working effect yet and therefore cause issues.
You could simplay replace the move bide with a different one through "remember attacks" and this issue should be solved.
