### ISSUE TITLE
How to use specials?

### ISSUE THREAD

**Issue by face515** [Unlucky-Life/ankimon#57]
In a Fennekin, for example, in the captured Pokémon menu, it says the ability is Blaze. How do I use Blaze?

**Comment by omfgroflmfaol** [comment]
These are not attacks; they are passive abilities:
https://pokemondb.net/ability
At the moment, they are not implemented to impact the battles inside of ankimon.

**Comment by Unlucky-Life** [comment]
@omfgroflmfaol @face515 Yes correct, right now they dont influence battle yet. But im planning to integrate them in the future.
