### ISSUE TITLE
Remembering moves

### ISSUE THREAD

**Issue by face515** [Unlucky-Life/ankimon#58]
What does remembering moves do?
![image](https://github.com/Unlucky-Life/ankimon/assets/141896602/15501280-e3a0-4b52-b038-7e56c2a5b814)

**Comment by CaptainDead** [comment]
Yeah I wanna know too

**Comment by CaptainDead** [comment]
Ohh I understood, its very easy, basically we can only choose limited number of attacks (5) as our mains from the total attacks
Example - 
![image](https://github.com/Unlucky-Life/ankimon/assets/139457914/afeecb69-6400-4944-a6b5-4c42d2fcd447)

Here I have total of 2 attacks but maybe as level increase I get more attacks I can choose from, and then I can click on 'remember' to select it and then a pop up asks us to replace another attack with the one we selected.
pop up- 
![Uploading image.png…]()

I guess we can select total of 5 attacks, in the above pic I have only two total attacks so thus in my five main attacks, those two are repeating.

**Comment by face515** [comment]
And after you've replaced an attack with an attack you remembered, can you remember the forgotten attack again?

**Comment by CaptainDead** [comment]
Yeah, its not really forgetting it, its more like equipping them, they wont be removed if you choose another over them.

**Comment by Unlucky-Life** [comment]
@face515 @CaptainDead Yes correct - The idea is, you can "remember attacks" of a pokemon, if you maybe by accident accept or replaced one of your attacks.

You can have a max of 4 Attacks.
