### ISSUE TITLE
Suggestion/Request - Give config option to manually Increase "reviewer_text_message_box" time | it disappears before I can read it fully.

### ISSUE THREAD

**Issue by CaptainDead** [Unlucky-Life/ankimon#59]
I title said it all, a lot of addons that shows pop-ups like puppy reinforce etc, give us an option in config to change the amount of time for which the pop up stays on screen, it would be great if you too could add such option if possible for "reviewer_text_message_box"
![image](https://github.com/Unlucky-Life/ankimon/assets/139457914/2307eb55-18e5-4343-8db8-e2e8247dcdb7)

Thanks for the amazing addon.🙏💯

**Comment by Unlucky-Life** [comment]
@CaptainDead Good idea ! This is a easy integration ! Thank you for the suggestion !
