### ISSUE TITLE
"caught first legendary" badge labelled as "first baby pokemon"

### ISSUE THREAD

**Issue by omfgroflmfaol** [Unlucky-Life/ankimon#68]
after catching the legendary pokemon uxie, the message said that I received the badge for catching my first baby pokemon. I already had that badge before. Seems that the labels got mixed up:
<img width="417" alt="image" src="https://github.com/Unlucky-Life/ankimon/assets/166659632/ced0dd92-a18b-411a-8ab6-e24f96709be0">

**Comment by face515** [comment]
Just a theory, but in an earlier issue, someone pointed out the order that types of pokemon showing up, with baby coming after normal pokemon. I would assume this progression is hard coded and just checks if it is different from the other categories you have found. After this occurs, it just hands out the next badge in the progression. This is what I think would be most likely.

**Comment by face515** [comment]
The link would be [here](https://github.com/Unlucky-Life/ankimon/issues/55#issuecomment-2049544187).

**Comment by Unlucky-Life** [comment]
@face515 @omfgroflmfaol yea @omfgroflmfaol is right that was a hard encoded issue: 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/eaab5c91-2796-45ae-8ecc-01e852c46b65)

Lul - but an easy fix

**Comment by Unlucky-Life** [comment]
@omfgroflmfaol easy fix, just replace the ` badges.json` file in the `addon_files `with this one:
https://github.com/Unlucky-Life/ankimon/blob/0a98291a8c4ba99b773dc58e53ad677598b4cd13/src/Ankimon/addon_files/badges.json
