### ISSUE TITLE
XP Bar issues

### ISSUE THREAD

**Issue by omfgroflmfaol** [Unlucky-Life/ankimon#74]
Hey there, after downloading the latest pre-release I noticed that #37 was still an issue - so in case you overlooked it, I put this here as a reminder that I suggested a fix for that issue in that thread (I can't reopen #37 myself).

Also, with the new reviewer xp bar in V1.269, I noticed that it does not update like the hp bar does - only when you start to study, it displays the current `mainpokemon_xp`, but it does not change when this value changes like the hp bar does. Haven't found the cause for that yet but will probably look into it more tomorrow :)

**Comment by Unlucky-Life** [comment]
@omfgroflmfaol hey thanks ! Back then i intented to do it that way. Now i think we can change this for the next update ! I reopened the issue. In terms of pull requests, this works easily by: https://docs.github.com/de/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?tool=webui

**Comment by Unlucky-Life** [comment]
@omfgroflmfaol have you found the issue yet for the mainpokemon xp ?

**Comment by Unlucky-Life** [comment]
@omfgroflmfaol i have found it ! Just a issue in update_life_bar. Use {} instead of ()
