### ISSUE TITLE
HP bar has excess health

### ISSUE THREAD

**Issue by Sabicool** [Unlucky-Life/ankimon#76]
<img width="1282" alt="image" src="https://github.com/Unlucky-Life/ankimon/assets/43723884/5a2ae800-27f8-4702-adda-5952875095ea">

I sometimes get instances where the HP is more than the maximum. In this example munchlax has 52 HP out of a maximum of 41 HP which results in the bar in the ankimon window extending beyond the limit.

**Comment by Unlucky-Life** [comment]
i see this sometimes happens due to miscalculation of max hp but i think i could find a work around
