### ISSUE TITLE
issue downloading resources

### ISSUE THREAD

**Issue by MarioFigueras** [Unlucky-Life/ankimon#80]
Hello! i'm having issues downloading the resources through the anki addon, i've tried a few of times but get stuck while downloading sprites.
the farthest i've managed to download was around 57%, each time in get stuck (left a whole night downloading and nothing) i have to delete the add-on and start downloading from zero again.

¿could you provide me all the resources directly to put them on the folder instead downloading them through anki?

thank you very much!!

**Comment by Unlucky-Life** [comment]
@MarioFigueras Hey no problem ! Here you go: https://we.tl/t-smatb6Uc4r
=> unzip these files in your addon folder: 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/4e1de183-4a8f-4bc6-96d7-81ff35b6229b)
=> in "user_files"

**Comment by Unlucky-Life** [comment]
your folder should look like this after: 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/3ea4547c-8be1-49c8-8c15-f9bce5eaa746)

**Comment by MarioFigueras** [comment]
that worked wonderful @Unlucky-Life !

thanks you so much and keep at good work!
