### ISSUE TITLE
Battle problems

### ISSUE THREAD

**Issue by Corrente007** [Unlucky-Life/ankimon#81]
the battel mode isnt working w/ Pokemons LV 100 plus

**Comment by Unlucky-Life** [comment]
> the battel mode isnt working w/ Pokemons LV 100 plus


Can you explain how this is not working and if your getting an error for this ?

**Comment by Corrente007** [comment]
The ankimon window is showing a black page, and i cant see both pokemon fighting, fothermore, there is a warning saying 
"Anki encountered a problem.
Please follow the
troubleshooting steps.
Add-ons possibly involved:
Ankimon by Unlucky-life"

<img width="1263" alt="Captura de Tela 2024-04-23 às 15 50 58" src="https://github.com/Unlucky-Life/ankimon/assets/167879816/171a6780-ae93-4af2-9d5b-85aaa4cdbc8f">

<img width="1268" alt="Captura de Tela 2024-04-23 às 15 50 36" src="https://github.com/Unlucky-Life/ankimon/assets/167879816/98f4e746-5a4e-4f5d-b47e-72601f82d0c4">

**Comment by face515** [comment]
@Corrente007 There is a chance you may have a missing back sprite error. See here[https://github.com/Unlucky-Life/ankimon/issues/45](url) for more info.

**Comment by Unlucky-Life** [comment]
> The ankimon window is showing a black page, and i cant see both pokemon fighting, fothermore, there is a warning saying "Anki encountered a problem. Please follow the troubleshooting steps. Add-ons possibly involved: Ankimon by Unlucky-life"
> 
> <img alt="Captura de Tela 2024-04-23 às 15 50 58" width="1263" src="https://private-user-images.githubusercontent.com/167879816/324959140-171a6780-ae93-4af2-9d5b-85aaa4cdbc8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTc2NTcsIm5iZiI6MTcxMzk1NzM1NywicGF0aCI6Ii8xNjc4Nzk4MTYvMzI0OTU5MTQwLTE3MWE2NzgwLWFlOTMtNGFmMi05ZDViLTg1YWFhNGNkYmM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMTE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmNiNTdjODJmNzkwMWNjMzMxMTM5NjZiMDM2OGIwYzg1YmNkMGRhNGZjMmUxY2Y5MTllZDNjOWMwYjJhYjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SsR2TRxKu6vGs_woqPs4plB5RnjZJm8EFLDDIFJPJ7s"> <img alt="Captura de Tela 2024-04-23 às 15 50 36" width="1268" src="https://private-user-images.githubusercontent.com/167879816/324958995-98f4e746-5a4e-4f5d-b47e-72601f82d0c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTc2NTcsIm5iZiI6MTcxMzk1NzM1NywicGF0aCI6Ii8xNjc4Nzk4MTYvMzI0OTU4OTk1LTk4ZjRlNzQ2LTVhNGUtNGY1ZC1iNDdlLTcyNjAxZjgyZDBjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMTE1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmM4MjEyNmU1MzAzYjNmMjhhNDI3NDgwODllMGEzODJmNjUwMjNjYzQxYTlmZWYzNjI1MWFkNWNjZDY5OTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mxf1_dZZq7e7SbGaCBZ_7DIkpslB5Mji6LbRa22AWjg">

=> have you used the version of ankimon over at ankiweb or the prerelease from this github ?

**Comment by Corrente007** [comment]
I didn't use the version on ankiweb or pre release :( and it happens with every pokemon lv 100 +

**Comment by sunrucong** [comment]
@Corrente007 how did you get your Pokemon to level past 100? I've been wanting to level mine further but haven't really looked into it before stumbling onto this post!

**Comment by Corrente007** [comment]
I'm good pokemon trainer kkk just kidding, i'm catching all the pokemons that i can using my strongest to fight

**Comment by sunrucong** [comment]
I mean my Pokemon and the wild Pokemon encounters both stop at lv. 100; is there a setting that you change to enable lvling past 100?

**Comment by Corrente007** [comment]
Oh  i didnt know about it, i never changed any configuration, i was just fighting
maybe thats why isnt working my fight battles

**Comment by Corrente007** [comment]
![Uploading Captura de Tela 2024-04-24 às 21.12.31.png…]()

**Comment by Corrente007** [comment]
<img width="574" alt="Captura de Tela 2024-04-24 às 21 13 14" src="https://github.com/Unlucky-Life/ankimon/assets/167879816/a3aa0652-ba39-4c35-a60d-180e9ed6125c">

**Comment by sunrucong** [comment]
Dang that's where I'm tryna be

@Unlucky-Life I'm sure you're busy but would you happen to know if this is a bug or a feature (or a bug as a feature)?

**Comment by Unlucky-Life** [comment]
@Corrente007 @sunrucong The implementation to view, use and play with other 100 lvl pokemon properly will come next week or the following week

**Comment by Unlucky-Life** [comment]
@sunrucong Hey i think i could do this ! No worries ;) => ill try to integrate this this or next update!

**Comment by sunrucong** [comment]
Amazing! Looking forward to it :D
