### ISSUE TITLE
Error Updating Ankimon Add-on

### ISSUE THREAD

**Issue by sunrucong** [Unlucky-Life/ankimon#86]
With the new ankimon update that was just released today, I am unable to update the add-on. The Error message includes identifying information, so I can share it with you @Unlucky-Life  separately if you'd like.

From what I can comprehend from the error message, it seems to be a permission issue, though I've never had that issue with this add-on (or any Anki add-on for that matter).

I submitted it on ankihub as well but I'm even less familiar with that site than github so I'm not sure if it was delivered correctly.

**Comment by Unlucky-Life** [comment]
@sunrucong ok hm i see, could you send it to me at leon.moegelin@gmail.com

It might be the sounds integration but im not sure

**Comment by Unlucky-Life** [comment]
I sent you an email back ! If this wont work let me know !


Hey Sunrucong, 
I think i know this error!
So it seems like something went wrong when updating (but this is easily fixed).
Simply do this:
1. Copy the complete user_files folder to a different location.
2. Then simply try to update Ankimon with this file:
https://github.com/Unlucky-Life/ankimon/releases/download/1.271/ankimon-1.271-anki21-ankiweb.ankiaddon
You can simply download it and run it (just double click, like you would install any application)
Note! Make sure to have anki closed when installing from the file - this should make sure that the update should run through.
3. copy back the content of user_files back into the addon_folder
That should help you be able to run the application !

If that wont work try this:
IMPORTANT: Before deinstalling the addon please copy paste all the files in user_files to a different location as a backup!
(Deinstall and Reinstall the Ankimon Addon from Ankiweb and after installing => just copy paste the user_files content into the user_files folder in your ankimon addon folder.)

It looks like the error you presented above was a Issue from Ankihub or atleast the issue happened while updating AnkiHub.
I think this should fix the issue !
If this wont work let me know !

**Comment by sunrucong** [comment]
Hey so looks like the first method didn't work, and I got the Start-Up Failed message; here's the debug info:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5788, in <module>
    rate_this_addon()
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5710, in rate_this_addon
    with open(rate_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ruper\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files\\rate_this.json'

**Comment by sunrucong** [comment]
The second method also failed and resulted in the same start-up failed message, but I think it might be due to something in my user_files folder b/c I tried starting it up without my user_files folder replacing the blank one and it started up fine

Here's the debug info for the second one

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5788, in <module>
    rate_this_addon()
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 5710, in rate_this_addon
    with open(rate_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ruper\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files\\rate_this.json'

**Comment by sunrucong** [comment]
Trying the third method from the email now!

**Comment by Unlucky-Life** [comment]
@sunrucong seems like you just need to paste this file into ur user_files

Just download this file 

https://github.com/Unlucky-Life/ankimon/blob/main/src/Ankimon/user_files/rate_this.json

and paste ir into your user_files folder

**Comment by sunrucong** [comment]
Oh interesting. Well the full redownload is happening right now anyway so
once that finishes I’ll install that file!

Thanks again and will let you know how it goes!

**Comment by sunrucong** [comment]
Alright the third method also didn't work; same method but now I didn't even put in my updated user_files folder, I'm gonna try the method in the follow-up email you mentioned.

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 193, in <module>
    extract_ids_from_file()
  File "C:\Users\ruper\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 188, in extract_ids_from_file
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ruper\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files\\mypokemon.json'

**Comment by sunrucong** [comment]
Adding that rate.json worked! So far so good!
