### ISSUE TITLE
The "pkmn_w.ttf" file is missing from the "addon_files" folder.

### ISSUE THREAD

**Issue by Foxy-null** [Unlucky-Life/ankimon#87]

**Comment by Unlucky-Life** [comment]
sadly i looked more into it and we need to ask the author before hand, it doesnt say on the website but in the readme: ```
Contact the creator for usage rights of pkmn_r.ttf, pkmn_s.ttf, and pkmn_w.ttf fonts.
¡Contact Information

Font creator: isc.subleader@gmail.com

```

**Comment by Foxy-null** [comment]
Have you already contacted the author? If not, and if you don't mind, I can contact the author instead of you.

**Comment by Unlucky-Life** [comment]
@Foxy-null the author is propably japanese so that would be awesome ! (for now i would place a txt file with the url in the addon_files folder for the next update) !

**Comment by Foxy-null** [comment]
I created an e-mail text to contact them and translated what I wrote into English with DeepL. Could you please check if it is the same as the content of the contact you are looking for?


`Email starts here:`

## Dear Mr. 鵺

Nice to meet you, my name is Foxy_null.

I am involved in the development of Pokemon add-ons for the memorization software "Anki".

I have contacted you regarding permission to use the Pokemon font you have created.

I was looking for a font that could faithfully reproduce the Pokemon battle screen, and I came across your font and was surprised at the high degree of reproduction.

Therefore, we would like to use your font in a Pokemon add-on for Anki, and would like to ask you for permission to use it under the GPL license.

We would also appreciate it if you could provide us with information on what we need to include on the license and how to do so.

Please check the official Anki website and the GitHub page of the Pokémon Add-on from the attached URL.

Thank you very much for your consideration.


### Sincerely

Foxy_null


## Attached.

- [Anki's official website](https://apps.ankiweb.net/)
- [GitHub page for Ankimon add-on](https://github.com/Unlucky-Life/ankimon)


Translated with DeepL.com (free version)

`End of the email`

`Original Japanese Text`
![image](https://github.com/Unlucky-Life/ankimon/assets/72304646/2c2c0d16-6291-4c68-a0b2-a496177e04e6)

**Comment by Unlucky-Life** [comment]
@Foxy-null Hey that would be perfect ! Let me know if he answers :)!

**Comment by Foxy-null** [comment]
### @Unlucky-Life Guess what?
He has **graciously agreed** to release the Pokémon font under the **MIT license**! A distribution repository for the font has been created on **[GitHub](https://github.com/nue-of-k/pkmn)**, which also contains the license. Check it out!

**Comment by Unlucky-Life** [comment]
@Foxy-null whoop whoop !
The E-Mail i got:
Dear Unlucky-life-san,

Thank you for using my pkmn fonts.
Now my fonts are available under the MIT License.
Please get them from my GitHub repository below:
https://github.com/nue-of-k/pkmn

Sincerly,
鵺 (Nue)

**Comment by Foxy-null** [comment]
Wow! He sent you an email too?! And in English?! What a nice person!

Anyway, now we can happily include the font in the add-on. I'm not very familiar with licensing issues, so please take care of the notation.

**Comment by Unlucky-Life** [comment]
Yes MIT License is perfect !
