### ISSUE TITLE
Error while attacking!

### ISSUE THREAD

**Issue by sunrucong** [Unlucky-Life/ankimon#88]
Happens randomly

![image](https://github.com/Unlucky-Life/ankimon/assets/161688926/1ccd4302-3755-4b08-ac34-ab7af3bd5d37)

**Comment by face515** [comment]
Does it happen with every pokemon or just some?

**Comment by sunrucong** [comment]
Just one, this lv. 30 something Victini I have right now, trying it out with more mons right now

**Comment by sunrucong** [comment]
Okay after like 15 minutes of no issues it happened with my lvl 8-10 wimpod specifically against a lv. 10 magearna

**Comment by sunrucong** [comment]
So far I've noticed it's only after I've studied for a while with each new session, though not sure if it's based on time or number of cards done

**Comment by sunrucong** [comment]
Yeah it's happening now even with my starter Charizard which hasn't had any issues for the longest time prior

**Comment by face515** [comment]
Just happened with my Anorith, maybe some sort of bug in code? I'm not very good at python, but I could attempt to take a look at the code

**Comment by Unlucky-Life** [comment]
@face515 @sunrucong there are some attack moves that dont correspond yet to any dmg or effect => thats when this throws an error

Its planned to create a workaround for this to not happen.

**Comment by sunrucong** [comment]
Hmm I think that may be the case, especially due to a move that the opponent Pokemon was doing, because I only noticed it happening on my main Charizard when I had that option to be attacked turned on (my Charizard has stuck with the same 4 dmg-dealing moves since hitting 100 a few weeks back without issue)

Once I turned that option off I haven't run into the issue on my Charizard so that checks out
