### ISSUE TITLE
Anki start-up error after update

### ISSUE THREAD

**Issue by nurkittel** [Unlucky-Life/ankimon#89]
Hi, 

I am encountering a Anki error message right after starting Anki after the update. If I press Cancel Anki will start though. Great update! Thanks!

Error code copy:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.4-arm64-arm-64bit

playsound is relying on a python 2 subprocess. Please use `pip3 install PyObjC` if you want playsound to run more efficiently.
===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-10-17T23:29, 'None', '']
Advanced Browser ['874215009', 2023-10-21T16:34, 'None', '']
AnkiHub ['1322529746', 2024-04-18T19:32, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-04-25T20:57, 'None', mod]
Projekt Anki Notetypes fr Ankizin  Co ['2058530482', 2024-04-10T18:14, 'None', mod]
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
Study Time Stats ['1247171202', 2024-02-24T17:59, 'None', '']
The KING of Button Add-ons ['374005964', 2024-01-27T11:19, 'None', '']

===IDs of active AnkiWeb add-ons===
1247171202 1322529746 1771074083 1908235722 2058530482 374005964 874215009

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Progress bar Fixed for Anki 24 by Shige ['1708250053', 2024-04-23T03:42, 'None', '']

**Comment by Unlucky-Life** [comment]
@nurkittel https://github.com/Unlucky-Life/ankimon/blob/2b0067fa2fe82f09fae84e35fdf6f8fcb1f0fd18/src/Ankimon/__init__.py => replace this file with your __init__.py in the Ankimon folder and on the next start up set sound_effects to False => the issue is the new sound library (playsound) and it seems to be a mac specific issue. Ill try to fix it asap

**Comment by nurkittel** [comment]
No sound and an error message from Anki after I set sound true and did 2 cards.

**Comment by Unlucky-Life** [comment]
but do you here any sounds ? no right ?

**Comment by nurkittel** [comment]
No
________________________________
