### ISSUE TITLE
Show a warning when a Pokemon is released

### ISSUE THREAD

**Issue by shigeyukey** [Unlucky-Life/ankimon#9]
Hello, this add-on is fantastic! 👍👍👍
I thought it might be nice to show a warning when a user releases a Pokémon. (I accidentally released Onix lol)

**Comment by Unlucky-Life** [comment]
oh rip :D this may be a good idea  to include that!

**Comment by Unlucky-Life** [comment]
=> this is included now for the next update !
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/809ae53b-92d5-4f21-9244-844ddb9672a0)
if no => 
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/2d30d31d-8c2c-412d-b965-d810e0b6cae9)
