### ISSUE TITLE
Error with the "previously caught" Pokeball on the reviewer window

### ISSUE THREAD

**Issue by ADEKBC** [Unlucky-Life/ankimon#92]
The Pokeball emblem fails to leave the screen when the battle switches from a Pokemon I have caught to one I still need to. For example, when battling a Chingling (I have caught), the ball is correctly present, but after beating the Chingling, Bronzong appeared (I had not yet caught). The ball remained through the entire battle with the Bronzong and every subsequent Pokemon regardless of having been caught or not. The only way to reset the ball and have it disappear on a Pokemon I still need to catch is to exit back to the main deck menu and reenter a deck review. Then, the Pokeball is gone as it should be. However, this requires that I know every Pokemon I have caught, which is the point of the Pokeball emblem update.

**Comment by Unlucky-Life** [comment]
@ADEKBC ok thats weird ill try it out and see whats the issue ! But thanks for the notice !

**Comment by Unlucky-Life** [comment]
This issue is solved for the next update.
