### ISSUE TITLE
"About Anki" on Mac replaced with AnkiMon License

### ISSUE THREAD

**Issue by ylime0124** [Unlucky-Life/ankimon#93]
<img width="757" alt="image" src="https://github.com/Unlucky-Life/ankimon/assets/69134574/731ff301-49b3-450c-b802-8bba867070bd">

**Comment by Unlucky-Life** [comment]
@ylime0124 oh damn, didnt know about this ! Thx for the notice!

**Comment by shigeyukey** [comment]
I may be wrong as I have not debugged on a Mac yet, adding `.setMenuRole(QAction.MenuRole.NoRole)` to `QAction` may help.
Previously such a Mac specific bug was solved that way. Like this.

```python
#__init__.py 7324
test_action13 = QAction("About and License", mw)
test_action13.setMenuRole(QAction.MenuRole.NoRole) # add
test_action13.triggered.connect(license.show_window)
mw.pokemenu.addAction(test_action13)
```

**Comment by shigeyukey** [comment]
Done, I confirmed it works on Mac. Adding `test_action13.setMenuRole(QAction.MenuRole.NoRole)` will make "About Anki" work correctly.
Maybe the reason for this is the Mac automatically assigns the most frequently used menus to the app. MenuRole.NoRole will disable it.
