### ISSUE TITLE
issues with downloading

### ISSUE THREAD

**Issue by monshino** [Unlucky-Life/ankimon#94]
this message shows up when I install the addon.. and no ankimon tab found on the side bar.
![image](https://github.com/Unlucky-Life/ankimon/assets/168537461/94109356-8e31-4dfd-a1f0-f4196a9e5246)

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22635

When loading Ankimon by Unlucky-life:
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1121, in generate_random_pokemon
    base_experience = search_pokeapi_db_by_id(id, "base_experience")
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1981, in search_pokeapi_db_by_id
    with open(str(pokeapi_db_path), "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*****\\AppData\\Roaming\\Anki2\\addons21\\1908235722\\user_files\\data_files\\pokeapi_db.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 2034, in <module>
    name, id, level, ability, type, stats, enemy_attacks, base_experience, growth_rate, hp, max_hp, ev, iv, gender, battle_status, battle_stats = generate_random_pokemon()
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1153, in generate_random_pokemon
    return generate_random_pokemon()  # Return the result of the recursive call
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\1908235722\__init__.py", line 1155, in generate_random_pokemon
    showInfo("Error", "Can't open the JSON File.")
  File "aqt.utils", line 296, in showInfo
TypeError: arguments did not match any overloaded call:
  QMessageBox(parent: Optional[QWidget] = None): argument 1 has unexpected type 'str'
  QMessageBox(icon: QMessageBox.Icon, title: Optional[str], text: Optional[str], buttons: QMessageBox.StandardButton = QMessageBox.NoButton, parent: Optional[QWidget] = None, flags: Qt.WindowType = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 1 has unexpected type 'str'

**Comment by Unlucky-Life** [comment]
@Victologo @monshino hey, ok no worries, here the link: https://send.vis.ee/download/0899a03b34e6edfa/#HpsBY06HjH8LcyH8T9B1lQ

=> download the zip file and unzip it inside of your user_files folder
![image](https://github.com/Unlucky-Life/ankimon/assets/77027147/fd7a731e-6514-4634-8cfe-37c982517927)
Meaning this location ^

**Comment by Unlucky-Life** [comment]
@Victologo @monshino Let me know if the issue persists !

**Comment by monshino** [comment]
@Unlucky-Life mind sharing this again?.. I was busy and didn't catch up to download the link.

**Comment by Unlucky-Life** [comment]
@monshino no worries here you go :) : https://pixeldrain.com/u/cwd49pLt

**Comment by monshino** [comment]
@Unlucky-Life that solved the issue. thank you so much for making this amazing add-on and for being so helpful! wish you all the best.
