### ISSUE TITLE
Review Error "name hp not defined"

### ISSUE THREAD

**Issue by Anki4Lyfe** [Unlucky-Life/ankimon#95]
<img width="663" alt="Screenshot 2024-05-02 at 6 52 43 PM" src="https://github.com/Unlucky-Life/ankimon/assets/168787061/d3fcc290-8b6f-4127-af2d-0aa7b8f83312">

This error comes up every 2-3 cards. Need to press OK in order to proceed.. really affects studying. Not sure how to fix?
Any help is appreciated!

**Comment by Unlucky-Life** [comment]
@Anki4Lyfe 
This error seems to be new.
Sometimes there is an issue with the certain wild pokemons.
Try to leave the reviewer an reenter the reviewer or try to close and open anki again.

If this doesnt solve the issue. Did you have any issues when downloading ?
