### ISSUE TITLE
"Previously Caught" Pokeball Indicator Doesn't Update Live

### ISSUE THREAD

**Issue by sunrucong** [Unlucky-Life/ankimon#96]
Hey @Unlucky-Life!

Thanks again for implementing the Pokeball indicator for previously caught Pokemon. It's the one QoL change that I appreciate the most!

I noticed that it won't update as the Pokemon cycle through automatically, but instead I have to exit out of the study session then re-enter for it to update.

For instance, if I was currently battling a Pikachu I already caught, it would correctly have the Pokeball indicator. However, if after defeating the Pikachu a new Lucario that I haven't caught before showed up, the Pokeball indicator would still be there. Only when I exit out of the study session such as with the "s" or "d" key and re-enter does the Pokeball indicator correctly go away for the uncaught Lucario.

The opposite scenario is also true, when facing an uncaught Pokemon and then subsequently facing a previously caught Pokemon, the Pokeball indicator does not pop up for that second, previously caught Pokemon unless I exit and re-enter.

This isn't the biggest issue as it doesn't break the add-on nor Anki itself, however having to exit and re-enter every time there's a Pokemon that I'm unsure about having caught before or not does tend to break up my study flow a bit.

Just wanted to bring this up, and if you want any more details I'd be glad to provide them!

**Comment by Unlucky-Life** [comment]
@sunrucong 
Hey thanks for the notice and detailed bug notice!
Ill try to fix this in the next update !

**Comment by Unlucky-Life** [comment]
for the next update this is solved :)! 👍
