### ISSUE TITLE
Spelling Error - "[Attack] has been choosen"

### ISSUE THREAD

**Issue by LeviLewinsky** [Unlucky-Life/ankimon#98]
This is super lame but it is a bit annoying because of how often you see it, but when your pokemon attacks the screen says "choosen" instead of "chosen" (e.g. Growl has been choosen.). I would really appreciate that small change to correct the misspelling. :)

**Comment by Unlucky-Life** [comment]
@LeviLewinsky damn definetly understandable - things you dont notice that 4am huh 😄 
added to the next update changes
