### ISSUE TITLE
error popup 

### ISSUE THREAD

**Issue by filofalful** [Unlucky-Life/ankimon#99]
<img width="305" alt="Screenshot 2024-05-06 at 10 33 05 PM" src="https://github.com/Unlucky-Life/ankimon/assets/169101530/bb7f2ef2-7697-4028-97ed-792cc62edd49">
i am getting this popup every 5 cards or so when i try to answer a card. when i press ok it moves onto the card after

**Comment by Unlucky-Life** [comment]
@filofalful Hi no worries ! This issue is fixed in the new prerelease: 
https://github.com/Unlucky-Life/ankimon/releases/tag/1.272
=> simply download the anki addon .apkg file and run it
